image: sap_nodejs_ubuntu_latest
script: 
 - npm install
 - npm test
notify:
  slack:
    webhook_url: $$SLACK_HOOK
    username: $$SLACK_USER
    channel: $$SLACK_CHANNEL
    on_started: true
    on_success: true
    on_failure: true
