#!/usr/bin/env node

"use strict";

var argv = require('optimist')
    .usage('Usage: $0 --conf <config-file>')
    .demand('conf')
    .describe('conf', 'location of configuration file')
    .boolean('dontask')
    .describe('dontask', 'Flag to skip initial confirmation')
    .argv;

require('./lib/app')(argv);

