(function(){ovi.provide("nokia.maps.heatmap._StackBlur");
(nokia.maps.heatmap.Os=function(){}).prototype={blurContext:function(e,l,h,d,c,g,b,f){e=this.blurData(e.getImageData(d,c,g,b),h,g,b,f||15);l.putImageData(e,d,c)},blurData:function(e,l,h,d,c){this.blurArray(e.data,l,h,d,c);return e},blurArray:function(e,l,h,d,c){c&1&&this.convolve(e,e,l,h,d,0);c&2&&this.convolve(e,e,l,h,d,1);c&4&&this.convolve(e,e,l,h,d,2);c&8&&this.convolve(e,e,l,h,d,3);return e},convolve:function(e,l,h,d,c,g){var b=(h+1)*(h+1),f,r,a,q,k,m,p,z,s,u=d*4,w=h+1,x,v=[{r:0,g:0,b:0,a:0,
next:null}];p=1;var y=["r","g","b","a"][g];a=2*h+1;for(var B,C,A;p<a;p++)v[p]={r:0,g:0,b:0,a:0,next:null},v[p-1].next=v[p];v[2*h].next=v[0];C=(d-1)*4;for(r=0;r<c;r++){m=r*u;f=e[m+g];k=f*w*(h+2)/2;a=f*w;for(p=0;p<=h;p++)v[p][y]=f;q=0;for(p=1;p<=h;p++)z=p<d?m+p*4:m+C,z=e[z+g],k+=z*(w-p),q+=z,v[h+p][y]=z;z=v[0];B=v[w];p=m;A=w*4;rowEnd=m+C;for(f=0;f<d;f++)if(l[p+g]=k/b,k-=a,s=f+w<d?p+A:rowEnd,s=e[s+g],q+=s,k+=q,a-=z[y],a+=B[y],q-=B[y],z[y]=s,z=z.next,B=B.next,p+=4,!k)for(;(x=(f+w)*4)<u&&e[m+g+x]==0;)f++,
p+=4}m=(c-1)*u;for(f=0;f<d;f++){e=f*4;r=l[e+g];k=r*w*(h+2)/2;a=r*w;for(p=0;p<=h;p++)v[p][y]=r;q=0;for(p=1;p<=h;p++)z=p<c?e+p*u:e+m,z=l[z+g],k+=z*(h-p+1),q+=z,v[h+p][y]=z;z=v[0];B=v[w];p=e;C=w*u;colEnd=e+m;for(r=0;r<c;r++)if(l[p+g]=k/b,k-=a,s=r+w<c?p+C:colEnd,s=l[s+g],q+=s,k+=q,a-=z[y],a+=B[y],q-=B[y],z[y]=s,z=z.next,B=B.next,p+=u,!k)for(;(x=r+w)<c&&l[x*u+g+e]==0;)r++,p+=u}}};ovi.provide("nokia.maps.heatmap._TileRenderer");
(function(e){function l(b,a){return b.stop-a.stop}var h=Math,d=h.floor,c=h.log,g=e.heatmap,b=e.util,f=b.d;g.Qs=ovi.Class({Statics:{DEFAULT_COLORS:{stops:{0:"#008","0.2":"#0b0","0.5":"#ff0","0.7":"#f00"},interpolate:!0}},initialize:function(d,a,e){d>>=a;this.Yw=a;this.Du=d;this.Uu=c(d)/c(2);this.dt=a=document.createElement("canvas");this.et=a.getContext("2d");this.ft=a.width=a.height=d*3;this.sp=new g.Os;var k=document.createElement("canvas"),h,a=e.interpolate,p=e.stops,d=[],z,s,u;k.width=256;k.height=
1;k=k.getContext("2d");for(h in p)p.hasOwnProperty(h)&&d.push({stop:parseFloat(h),value:p[h]});p=d.length;p<2&&b.d("The heat map colors definition must have at least two values.");d.sort(l);d[0].stop>0&&d.unshift({stop:0,value:d[0].value});d[p-1].stop<1&&d.push({stop:1,value:d[p-1].value});p=d.length;h=k.createLinearGradient(0,0,256,0);for(z=0;z<p;z++)isNaN(d[z].stop)&&f("Stop offset for heat map color definitions must be parseable floats."),!a&&s&&(u=s.stop+(d[z].stop-s.stop)/2,h.addColorStop(u,
s.value),h.addColorStop(u,d[z].value)),h.addColorStop(d[z].stop,d[z].value),s=d[z];k.fillStyle=h;k.fillRect(0,0,256,1);this.rt=k.getImageData(0,0,256,1).data;this.Eu=e.interpolate},paint:function(b,a,c,f,e,g,l,s,u){var a=this.Du,f=this.et,w,x=g==="density"?2:1,v=x,c=h.min(c+x,this.Uu),y,B,C,A,D,x=this.ft,E;e&&g==="value"?this.wv(b,l,s,u,f,a,x):(f.fillStyle=e?"#080":"#000",f.fillRect(0,0,x,x));for(;v<=c&&l+v<=b.fb;v++){A=a>>v;offset=a-A;E=g==="density"?127+d(128/(1<<c-v)):255;D=(1<<v)+2;e=this.gu(b,
v,l,s,u,!1);for(y=e.length;y--;)if(B=y%D,C=y/D<<0,w=e[y])w=b.gk(w.average),f.fillStyle="rgba("+w+","+E+",0,1)",f.fillRect(B*A+offset,C*A+offset,A,A);this.sp.blurContext(f,f,A,offset,offset,a+2*A,a+2*A,3)}b=this.st(f.getImageData(0,0,x,x),this.rt,this.Eu);f.putImageData(b,0,0);return[this.dt,a]},st:function(b,a,c){for(var d=b.data,f,e,g=0,h=d.length;g<h;g+=4)f=d[g],e=d[g+1],a.length==4&&(f=0),d[g]=a[f*4],d[g+1]=a[f*4+1],d[g+2]=a[f*4+2],d[g+3]=a[f*4+3]*(c?e/255:e<10?0:1);return b},wv:function(b,a,c,
f,e,g,h){var l,u,w;for(w=-1;w<=1;w++)for(u=-1;u<=1;u++)l=(l=b.getQuad(a,c+w,f+u,!0))?b.gk(l.average):128,e.fillStyle="rgba("+l+",128,0,1)",e.fillRect((u+1)*g,(w+1)*g,g,g);this.sp.blurContext(e,e,g-d(g/10),0,0,h,h,3)},gu:function(b,a,c,d,f,e){var g=1<<a;f<<=a;d<<=a;return b.getQuads(c+a,d-1,d+g,f-1,f+g,e)}})})(nokia.maps);ovi.provide("nokia.maps.heatmap._TileHashMap");
(function(e){var l=e.heatmap,h=e.geo.mercator,d=e.util.Nf,e=Math,c=e.round,g=e.log,b=e.pow,f=l.dj=new ovi.Class({initialize:function(b,c,d){var f=0;this.fb=b>30?30:b<0?0:b;this.fm=d||this.fb;c==="value"?(this.Tn=r,this.gk=this.Yu):(this.Tn=a,this.gk=this.Xu);this.dc=[];this.yd=[];for(f=0;f<=b;f++)this.yd[f]=[],this.dc[f]=new q;this.dk=-1/0;this.Mh=1/0;this.xj=null},yd:null,dc:null,fb:null,addDataPoint:function(a){var b=h.latLngToMapPoint(a.latitude,a.longitude),c=this.fb,d=b.x>>30-this.fb,b=b.y>>
30-this.fb,f,e=this.Tn;f=a.value==null?1:a.value;if(f>this.dk)this.dk=f,this.xj=this.dk-this.Mh;if(f<this.Mh)this.Mh=f,this.xj=this.dk-this.Mh;for(;c>=0;){this.yd[c][b]||(this.yd[c][b]=[]);f=this.yd[c][b][d]||(this.yd[c][b][d]=new e);f.addDataPoint(a,this.fb,c);if(this.dc[c].minSum>f.sum)this.dc[c].minSum=f.sum;if(this.dc[c].maxSum<f.sum)this.dc[c].maxSum=f.sum;if(this.dc[c].minAverage>f.average)this.dc[c].minAverage=f.average;if(this.dc[c].maxAverage<f.average)this.dc[c].maxAverage=f.average;c--;
d>>=1;b>>=1}},getQuad:function(a,b,c,f){c=d(c,1<<a);return(quad=(rowInRange=b>=0&&b<=(1<<a)-1)&&this.yd[a]&&this.yd[a][b]&&this.yd[a][b][c]||null)?quad:f&&a>=0?this.getQuad(a-1,b>>1,c>>1,f):quad},getQuads:function(a,b,c,d,f,e){for(var g=d,h=[];b<=c;b++){for(;g<=f;g++)h.push(this.getQuad(a,b,g,e));g=d}return h},clear:function(){f.call(this,this.fb,this.Tn==r?"value":"density",this.fm)},Mw:function(){var a,b,d=this.dc,f=this.fb,e=0;b=d[this.fb].maxSum;for(a=this.fb;a>=0;a--)if(d[a].maxSum===b)e=a;else break;
b=d[0].maxSum;for(a=0;a<=e;a++)if(b===d[a].maxSum)f=a;else break;if(e>this.fm)e=this.fm;a=c(f+(e-f)/2);this.gamma=g(0.5)/g(d[a].maxAverage);this.rx=f;this.qx=e},gk:null,Xu:function(a){return this.gamma!=null?c(b(a,this.gamma)*255):127},Yu:function(a){return this.xj?c((a-this.Mh)/this.xj*255):127}}),r=l.dj.ValueQuad=function(){this.count=this.sum=this.average=0},a,q;r.prototype={addDataPoint:function(a){this.sum+=a.value!=null?a.value:1;this.average=this.sum/++this.count}};a=l.dj.DensityQuad=function(){this.count=
this.sum=this.average=0};a.prototype={addDataPoint:function(a,c,d){this.count++;this.sum+=a.value||1;this.average=this.sum/b(2,(30-d)*2)}};q=l.dj.Level=function(){this.minSum=this.minAverage=Number.POSITIVE_INFINITY;this.maxSum=this.maxAverage=Number.NEGATIVE_INFINITY}})(nokia.maps);ovi.provide("nokia.maps.heatmap.Overlay");
(function(e){var l=e.util,h=e.heatmap,d=l.Coroutine,c=h.dj,g=h.Qs,b=e.map.provider.Tile,f=e.dom.Page.browser,r=f.mozilla&&f.fullVersion=="7.0";h.Overlay=new ovi.Class({Extends:e.map.provider.TileProvider,initialize:function(a){e.dom.supportsCanvas||l.jg("Heat maps are not supported in this environment, due to missing canvas support.");var b=Math,a=a||{};this._super(a);this.height=this.width=256;this.type=this.type||"density";this.sampleDepth=this.sampleDepth==null?4:b.min(b.max(this.sampleDepth,1),
8);this.assumeValues=!!this.assumeValues;this.dataMax=this.dataMax||this.max;this.coarseness=this.coarseness==null?1:b.min(b.max(this.coarseness,0),3);this.opacity=a.opacity||0.8;this.colors=this.colors||g.DEFAULT_COLORS;this.kg=new c(this.max+this.sampleDepth,this.type,this.dataMax);this.Cw=new g(this.width,this.coarseness,this.colors);this.Tf=[];this.bi={};this.Fn(this)},Statics:{TYPE_DENSITY:"density",TYPE_VALUE:"value"},addData:function(a){for(var b=0,c=a.length;b<c;b++)this.kg.addDataPoint(a[b]);
this.type==="density"&&this.kg.Mw();this.update()},clear:function(){this.kg.clear();this.update()},create:function(a,c,f,e){var g=a<=this.max&&a>=this.min,h=this.assumeValues,l,r,w=new b(e,0,this);if(this.kg.getQuad(0,0,0)){if(g){if(!h){l=this.kg.getQuads(a,c-1,c+1,f-1,f+1);for(r=l.length;r--&&!h;)l[r]!=null&&(h=!0)}h&&(this.bb[e]=w,this.Tf.push({id:e,level:a,row:c,col:f}),d.signal(this.bi))}}else w.state=!1;w.state=g&&h?void 0:!1;return w},Fn:d.create("nokia.maps.heatmap.Overlay#_paintCo",function(a){for(var a=
a.that,b,c=this.width,f,e,g;f=a.Tf.shift();)if(b=this.bb[f.id])if(e=document.createElement("canvas"),e.width=e.height=c,g=e.getContext("2d"),f=a.Cw.paint(a.kg,c,a.sampleDepth,a.dataMax,a.assumeValues,a.type,f.level,f.row,f.col),g.drawImage(f[0],f[1],f[1],f[1],f[1],0,0,c,c),r&&g.drawImage(e,0,0),b.data=e,b.state=!0,this.finishRequest(b.id,b,1),d.shallYield())return d.yield();return d.wait(a.bi)},{useAnimationFrame:!0},"that")})})(nokia.maps);ovi.provide("nokia.maps.heatmap._packaging.package-heatmap");})();
