(function(){(function(i){function n(b){for(var b=b.split("."),e=this,j=b[0]==="window"?1:0;j<b.length;j++)e=e[b[j]]||(e[b[j]]={});return e}var r=n(i.split(".")[0]),a;a=r.Features={};if(!(a.load&&typeof a.load==="function")){var f=function(){return!0},h={},o={},p=function(){for(var b in o)o.hasOwnProperty(b)&&o[b]&&!o[b].cancelled&&o[b].load()},k=function(b,e){for(var j=h[b],s=j?j.length:0;s--;)if(j[s].name===e)return j[s];throw"InvalidArgument: Feature implementation [$1] does not exist in the registry.".replace("$1",
b+":"+e);},l=function(b,e){var j;if(!e||e==="auto")a:{for(var s=(j=h[b])?j.length:0,a=0;a<s;a++)if(j[a].readyState==="complete"||j[a].readyState==="loading"){j=j[a];break a}for(a=0;a<s;a++)if(j[a].detector()){j=j[a];break a}j=null}else j=e==="none"?null:k(b,e);return j},d=function(b){var b=b||f,e={},j,a,c;for(a in h)if(h.hasOwnProperty(a)){j=[];for(c=0;c<h[a].length;c++)b(h[a][c])&&j.push(h[a][c].name);j.length>0&&(e[a]=j)}return e},e,c=0,q=function(b,e,a,c,d,g,l){this.featureName=b;this.name=e;this.loadPath=
a;this.detector=c||f;this.dependencies=d;this.overrides=g;this.charset=l||"UTF-8";this.readyState="uninitialized"};q.prototype={onWrite:function(b){this.readyState="loading";b&&p()},onLoad:function(b){b&&this.onWrite(b);this.readyState="complete";p()},canLoad:function(b,e){for(var a=this.dependencies,c=a?a.length:0,d;c--;){if(b[a[c]]==="none")throw"InvalidState: Feature [$1] requires [$2] but it has been explicitly set to 'none'. Aborting loader.".replace("$1",this.featureName).replace("$2",a[c]);
d=l(a[c],b[a[c]]||"auto");if(!d)throw"InvalidArgument: Feature implementation [$1] does not exist in the registry.".replace("$1",a[c]);if(d.readyState==="uninitialized"||!e&&d.readyState==="loading")return!1}return!0},writeSync:function(b){this.readyState="loading";b.write('<script type="text/javascript" charset="$ENC$" src="$SRC$"><\/script>'.replace("$SRC$",this.loadPath).replace("$ENC$",this.charset));this.onLoad(!0)},writeAsync:function(b,a,e){this.readyState="loading";var c=this,d=b.createElement("script");
a&&(d.async=!1);d.type="text/javascript";d.charset=this.charset;d.onload=d.onreadystatechange=function(){var e=d.readyState;if(!e||/^(?:loaded|complete)$/i.test(e))d.onload=d.onreadystatechange=null,c.onLoadCallback&&c.onLoadCallback(b),c.onLoad(a)};d.onerror=function(b){e(b)};d.src=this.loadPath;b.getElementsByTagName("head")[0].appendChild(d);this.onWrite(a)}};q.prototype.featureName=null;q.prototype.onLoadCallback=q.prototype.onLoadCallback;q.prototype.readyState=null;var g=function(b){this.matrix=
b};g.prototype={resolve:function(b,a){var e={},c,d=this.matrix,g=b.length,l,f,q;if(a)for(c in a)e[c]=a[c];for(;g--;)for(l=(c=d[b[g]])?c.length:0;l--;)q=c[l]&&c[l].split("="),f=q[0],h[f]&&this.addToMap(q[0],q.length===2?q[1]:null,e);return e},addToMap:function(b,a,e){!a&&!e[b]?e[b]="auto":!e[b]||e[b]=="auto"?e[b]=a:this.doesOverride(b,a,e[b])&&(e[b]=a)},doesOverride:function(b,e,a){if(!e)return!1;var c=(b=k(b,e).overrides)&&b.length;if(!b)throw"InvalidState: Cannot resolve package conflict between [$1] and [$2]. There is no override specification.".replace("$1",
e).replace("$2",a);for(;c--;)if(b[c]===a)return!0;return!1}};var t=function(b,a,d,g,l){g=g||document;this.requested=b;this.onSuccess=a||f;this.onError=d||function(b){throw b;};this.doc=g;this.detectLanguage();l===void 0?(this.inHead=g.readyState!=="complete",this.writeSync=e==null?e=g.createElement("script").async:e):this.inHead=this.writeSync=l;this.id=c++;o[this.id]=this};t.prototype={onFinished:function(b){delete o[this.id];if(b)this.onError(b);else this.onSuccess()},load:function(){var b=this.requested,
e,a,c=!0,d=this;try{for(a in b)h[a]&&(e=l(a,b[a]))&&this.loadSingle(e,b,this.inHead,this.writeSync,function(b){d.onFinished(b)})&&(c=!1);c&&this.onDone()}catch(g){this.onFinished(g),this.onFinished=f}},detectLanguage:function(){var b=this.requested.language;if(b)this.requested.language=r.Language.detect(b)},onDone:function(){if(!this.done){var b=this;this.inHead||window.setTimeout(function(){b.onFinished()},1);this.done=!0}},loadSingle:function(b,a,e,c,d){if(b.readyState==="complete")return!1;else if(b.readyState===
"loading")return!0;var g,f;if(b.canLoad(a,c))e?b.writeSync(this.doc,this.id,d):b.writeAsync(this.doc,c,d);else{b=b.dependencies;for(g=b.length;g--;)f=l(b[g],a[b[g]]||"auto"),this.loadSingle(f,a,e,c,d)}return!0}};t.prototype.onFinished=t.prototype.onFinished;t.prototype.id=null;t.prototype.doc=null;a.loaders=o;a.features=h;a._detectors={};a.get=l;a.add=function(b,a,e,c,d,g,l){if(!b||!a||!e)throw"InvalidArgument: A feature implementation must have at least a feature name, name and a loadPath.";(h[b]||
(h[b]=[])).push(new q(b,a,e,c,d,g,l))};a.isLoaded=function(b,a){return k(b,a).readyState==="complete"};a.load=function(b,a,e,c,d){(new t(b,a,e,c,d)).load()};a.getFeatureMap=function(){return d(function(a){return a.featureName!="base"})};a.getLoadedMap=function(){return d(function(a){return a.featureName!="base"&&a.readyState==="complete"})};a.setFeatureMatrix=function(e){a.featureMatrix=new g(e)};a.getFeaturesFromMatrix=function(e,c){return a.featureMatrix.resolve(e,c)};n("nokia.maps").Features=a}})("nokia.maps",
this);
(function(i,n){var r=i.split(".")[0],a=i.split(".")[1],f,h=n.navigator,o=h.userLanguage||h.language,h=function(a){var d={},e;for(e=a.length;e--;){var c=a[e].split(" "),f=c[0],g={};g.key=f;g.iso639_1=f.substr(0,2);g.marc=c[1];g.locale=c[2];d[f]=g}return d}(["al ALB","ar ARA ar-SA","be BEL","bg BUL bg-BG","bn BEN","bs BOS","ca CAT","cs CZE cs-CZ","cy WEL","da DAN da-DK","de GER de-DE","el GRE el-GR","en ENG en-GB","en-us ENG en-US","es SPA es-ES","eu BAQ","et EST et-EE","fa IRN fa-IR","fi FIN fi-FI","fr FRE fr-FR",
"ga GLE","gl GLG","hi IND hi-IN","he HBR","hr SCR hr-HR","hu HUN hu-HU","id IND id-ID","id-id IND id-ID","in-id IND id-ID","is ICE is-IS","it ITA it-IT","ja JPN","km KHM","ko KOR ko-KR","ky KIR","lt LIT lt-LT","lv LAV lv-LV","me MNE","mi MAO","mk MAC","mn MON","mo MOL","ms MAY ms-MY","nl DUT nl-NL","no NOR no-NO","pl POL pl-PL","pt POR pt-PT","pt-br BRA pt-BR","py PYN","ro RUM ro-RO","ru RUS ru-RU","sk SLO sk-SK","sl SLV","sr SRB sr-RS","sv SWE sv-SE","sw SWA","ta TAM","th THA th-TH","tl PHL tl-PH",
"tr TUR tr-TR","uk UKR uk-UA","ur PAK ur-PK","vi VNM vi-VN","zh CHI zh-CN"]),p,k;n[r]||(n[r]={});f=n[r];f.Language={definitions:h,detect:function(a){var d=f.Features&&f.Features.getFeatureMap().language||["en-US"],e=d?d.length:0,c,q={},g=[];if(!p){for(k=d&&d.length>0?d[0]:"en-US";e--;)if(c=d[e].toLowerCase(),(c=this.getDefinition(c))&&c.locale&&!q[c.key])q[c.key]=c,g.push(c.locale);p=q}return a==="none"?"en-US":this.autoDetect(a)},autoDetect:function(a){var d=k,a=this.getDefinition(!a||a==="auto"?
o||d:a,p);if(!a||!a.locale)a=this.getDefinition(d,p);return a.locale},getDefinition:function(a,d){var d=d||this.definitions,e=a.toLowerCase();return e.length>=2?d[e]||d[e.substr(0,2)]:null},a:function(){nokia.maps.resources={};nokia.maps.resources.ui={};nokia.maps.resources.ui.i18n={}},setTranslations:function(a){var a=this.getDefinition(a),d=a.locale,e=d.substr(0,2).toLowerCase(),d=d.substr(3,2).toUpperCase(),c;nokia.maps.resources||this.a();c=nokia.maps.resources.ui.i18n;if(c[e]&&c[e][d])this.translations=
(new Function("return "+c[e][d].translation.json+";"))(),this.language=a}};a?(f[a]=f[a]||{},f[a].language={},f[a].language.Info=f.Language):(f.language={},f.language.Info=f.Language)})("nokia.maps",this);(function(){var i=[0.1];i.pop();i.push("");if(i[0]!==""){var n=function(i,a){var f=i[a];i[a]=function(){this.length||(this[0]="")||(this.length=0);return f.apply(this,arguments)}},i=Array.prototype;n(i,"push");n(i,"splice")}})();
(function(i,n){function r(a){var c=d[a];return function(a){f.Settings.set(c,a)}}var a=i.split(".")[0],f,h={},o,p,k=!1,l,d={appId:"app_id",authenticationToken:"app_code",app_id:"appId",app_code:"authenticationToken"};n[a]||(n[a]={});f=n[a];p=f.Features;o=f.Language;f.Settings=a={addObserver:function(a,c,d){(h[a]?h[a]:h[a]=[]).push({callback:c,context:d})},removeObserver:function(a,c,d){var a=h[a],g,f=0;if(a)for(g=a.length;f<g;)a[f]===c&&a[f+1]===d&&a.splice(f,2),f+=2},set:function(a,c,d){var g=this[a];
this[a]=this[a+"Setter"]?this[a+"Setter"](c):c;this.b(a,c,g,d)},b:function(a,c,d,g){if((a=h[a])&&(d!==c||g))for(g=a.length;d=a[--g];)d.callback.call(d.context||null,c)},lockLanguage:function(){k=!0},defaultLanguageSetter:function(a){var c;if(k)throw Error("Illegal: defaultLanguage cannot be set after a display was initialized");a=nokia.maps.config&&nokia.maps.config["language.overrideDetection"]?a==="auto"?o.detect(a):a:o.detect(a)||"en-US";try{c=p&&!p.isLoaded("language",a)}catch(d){c=!0}c?(c=p.getLoadedMap(),
p.load({language:a},null,null,null,!c.language||c.language.length===0?void 0:!1)):o.setTranslations(a);return a},languageLoaded:function(a){var c=k;c&&(k=!1);o.setTranslations(a);this.set("defaultLanguage",a,!0);c&&(k=!0)},defaultLanguage:"",appId:"",authenticationToken:"",app_id:"",app_code:""};for(l in d)d.hasOwnProperty(l)&&a.addObserver(l,r(l))})("nokia.maps",this);nokia.maps.Features._detectors["capturing-capturing"]=function(){return!0};
nokia.maps.Features._detectors["clustering-clustering"]=function(){return!0};nokia.maps.Features._detectors["heatmap-heatmap"]=function(){return!0};nokia.maps.Features._detectors["ui-ovi_enterprise"]=function(){return!0};
nokia.maps.Features._detectors["ui-nokia_enterprise"]=function(){var i=navigator.userAgent.toLowerCase(),n=function(){var a=document.createElement("canvas");if(!a||!a.getContext)return!1;return typeof a.getContext("2d").fillText==="function"}(),r=document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1"),a=i.match(/msie/)&&!window.opera&&!n,i=i.match(/msie\s7/);return n||r||a&&!i};nokia.maps.Features._detectors["advsearch-nokiaenterprise"]=function(){return!0};
nokia.maps.Features._detectors["search-nokiaenterprise"]=function(){return!0};nokia.maps.Features._detectors["advrouting-nlp"]=function(){return!0};nokia.maps.Features._detectors["routing-nlp"]=function(){return!0};nokia.maps.Features._detectors["positioning-w3c"]=function(){var i=!1;try{i=!(!navigator||!(navigator.geolocation&&typeof navigator.geolocation.getCurrentPosition==="function"))}catch(n){}return i};nokia.maps.Features._detectors["behavior-touch"]=function(){return!0};
nokia.maps.Features._detectors["behavior-all"]=function(){return!0};nokia.maps.Features._detectors["map-render-display"]=function(){return!0};nokia.maps.Features._detectors["gfx-vml"]=function(){var i=navigator.userAgent.match(/MSIE ([\d.]+)/);return!!i&&i[1]<9};nokia.maps.Features._detectors["gfx-svg"]=function(){return document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")};
nokia.maps.Features._detectors["gfx-canvas"]=function(){try{var i=typeof document.createElement("CANVAS").getContext("2d").fillText==="function"&&!/MSIE (\d+\.\d+);/.test(navigator.userAgent)}catch(n){}return i||!1};nokia.maps.Features._detectors["kml-kml"]=function(){return!0};this.nokia.maps=this.nokia.maps||{};this.nokia.maps.build="nokiamapsapi-ee-2.5.4-Oberon-20140729-w30-r79a848e48e6a9aa597e37fcc84576678ef70ad64";var m=this.nokia.maps,u=m.config||{};u.reporter={full:"http://mapcreator.nokia.com/mapfeedback/widget/1.1.6/"};
u.packages=u.packages||{search:[{name:"nokiaenterprise"}],advsearch:[{name:"nokiaenterprise",dependencies:["search"]}],routing:[{name:"nlp",dependencies:["map"]}],advrouting:[{name:"nlp",dependencies:["routing"]}],positioning:[{name:"w3c"}],map:[{name:"render-display",dependencies:["gfx","language"]}],behavior:[{name:"all"},{name:"touch"}],gfx:[{name:"canvas"},{name:"svg"},{name:"vml"}],ui:[{name:"nokia_enterprise",dependencies:["gfx","map","language"]},{name:"ovi_enterprise",dependencies:["map",
"language"]}],language:[{name:"en-US"},{name:"en-GB"},{name:"de-DE"},{name:"es-ES"},{name:"zh-CN"},{name:"fr-FR"},{name:"ru-RU"},{name:"it-IT"}],kml:[{name:"kml",dependecies:["map"]}],heatmap:[{name:"heatmap",dependencies:["map"]}],clustering:[{name:"clustering",dependencies:["map"]}],capturing:[{name:"capturing",dependencies:["ui","gfx"]}]};u.externalPackages=u.externalPackages||{};
u.featureMatrix=u.featureMatrix||{maps:["gfx","behavior","map","ui","positioning","search","advsearch","routing","advrouting","kml","heatmap","clustering","capturing","language"],all:["gfx","behavior","map","ui","positioning","search","advsearch","routing","advrouting","kml","heatmap","clustering","capturing","language"]};u.routing=u.routing||{baseUrl:"http://route{serviceMode}.nlp.nokia.com/routing/6.2/","secure.baseUrl":"https://route{serviceMode}.nlp.nokia.com/routing/6.2/",protocol:"nokia.maps.routing.navteq.protocolV62"};
u.copyrightsInclude=u.copyrightsInclude||"nokia.maps.map._Copyright";u.copyrights=u.copyrights||"http://1.{service}.maps{serviceMode}.api.here.com/maptile/2.1/copyright/newest";u.assetsPath=u.assetsPath||"assets/ovi/mapsapi";u.adbarCss=u.adbarCss||"adbar.css";u["language.warnOnMissingTranslation"]=u["language.warnOnMissingTranslation"]||!1;u.tileProviders=u.tileProviders||"nokia.maps.map.js.enterpriseTileProviders";m.config=u;nokia.maps.config=this.nokia.maps.config;
(function(){function i(a){e=a.dependencies||[];e.push("base");l=p+"-"+a.name;c.add(p,a.name,f+l+".js",c._detectors[l],e,a.overrides)}function n(a){for(var c=/([\\?&]([^=]+)=([^&#]+))/g,b,d={};b=c.exec(a);)d[b[2]]=b[3];return d}function r(){if(o["jsl.js"])return o["jsl.js"];for(var a="jsl.js".replace(".","\\."),c=document.getElementsByTagName("script"),b=c.length,a=RegExp("^(.*\\/"+a+".*|"+a+".*)");b--;)if(a.test(c[b].src))return o["jsl.js"]=c[b].src,o["jsl.js"];throw"InternalError: could not locate jsl.js in the environment.";
}var a=nokia.maps.config,f,h,o={};if(!a.developmentMode&&!a.assetsPath)throw"Internal Error: no asset path has been specified";f=a.loadPath||function(a){a=a.split("/").slice(0,-1);return a.join("/")+(a.length>0?"/":"")}(r());h=a.params||n(r());var p,k,l,d,e,c=nokia.maps.Features,q=this;for(p in a.packages){k=a.packages[p];for(d=0;d<k.length;d++)i(k[d])}if(a.externalPackages)for(p in a.externalPackages){k=a.externalPackages[p];for(d=0;d<k.length;d++)c.add(p,k[d].name,(k[d].url?k[d].url:f)+k[d].fileName,
k[d].detector,k[d].dependencies,k[d].overrides)}c.add("base","noovi",f+"base_noovi.js",function(){return q.ovi&&q.ovi.win});c.add("base","withovi",f+"base.js",function(){return!q.ovi||!q.ovi.win});a.params=h;a.baseUrl=f;a.featureMatrix?(c.setFeatureMatrix(a.featureMatrix),a=h["with"]?h["with"].split(","):["maps"],delete h["with"],a=c.getFeaturesFromMatrix(a,h)):a=h;h.blank||c.load(a,null,function(a){throw a;})})("nokia.maps",this);})();