(function(){ovi.provide("nokia.maps.util.ColorHelper");
(function(e){function l(a){var b;if(a.charAt(0)==="#")b=f[a.length]?a:null;else if(a.substr(0,3)==="rgb"){b=a.match(/\d+(\.\d+)?/g);var c=b.length;b=c>2&&c<5?["#",d(+b[0]),d(+b[1]),d(+b[2]),c>3?d(+b[3]*255):"ff"].join(""):null}b||e.d("Invalid color definition: "+a);return b}function h(a){return!/^(#|rgb).*/.test(a)}function d(a){return a<16?"0"+g(a).toString(16):g(a).toString(16)}function c(a){a=b(a,16);return(a<<4)+a}var g=Math.round,b=parseInt,f={4:function(a){return["#",a.charAt(1),a.charAt(1),
a.charAt(2),a.charAt(2),a.charAt(3),a.charAt(3),"ff"].join("")},5:function(a){return["#",a.charAt(1),a.charAt(1),a.charAt(2),a.charAt(2),a.charAt(3),a.charAt(3),a.charAt(4),a.charAt(4)].join("")},7:function(a){return a+"ff"},9:function(a){return a}},r={4:function(a){return[c(a.charAt(1)),c(a.charAt(2)),c(a.charAt(3)),255]},5:function(a){return[c(a.charAt(1)),c(a.charAt(2)),c(a.charAt(3)),c(a.charAt(4))]},7:function(a){a=b(a.substring(1),16);return[a>>16&255,a>>8&255,a&255,255]},9:function(a){a=b(a.substring(1),
16);return[a>>24&255,a>>16&255,a>>8&255,a&255]}};e.ColorHelper={toInternal:function(a){return h(a)?a:(a=l(a),f[a.length]?f[a.length](a):a)},toRGBA:function(a,b){return h(a)?[0,0,0,255]:(b||(a=l(a)),r[a.length](a))},getHex3:function(a,b){return h(a)?a:(b||(a=l(a),a=f[a.length]?f[a.length](a):a),a.substr(0,7))},getAlpha:function(a,c){return h(a)?1:(c||(a=l(a),a=f[a.length]?f[a.length](a):a),b(a.substr(7,2),16)/255)},toRandomRGBA:function(a,b){if(h(a))return"000000ff";else{for(var a=this.toRGBA(a,b),
c=0;c<4;c++)a[c]=""+d(c<3?Math.floor(Math.random()*(a[c]-0+1))+0:a[c]);return a.join("")}}}})(nokia.maps.util);ovi.provide("nokia.maps.util.proto");(function(){var e={}.toString,l=nokia.maps.util.proto=function(h,d,c,g){var b=Function(),f,r;b.prototype=d;b=new b;for(f in h)h.hasOwnProperty(f)&&(b[f]=c&&f in d&&e.call(r=h[f])==="[object Object]"?l(r,d[f],c):h[f]);if(c&&!g)for(f in d)if(d.hasOwnProperty(f)&&(r=d[f])===b[f]&&e.call(r)==="[object Object]")b[f]=l(0,r,c);return b}})();ovi.provide("nokia.maps.util.Cache");
(function(e){function l(a,b,c,d){this.c=a;this.J=b;if(this.f!==d)this.f=d;if(c)(c.Z=this).X=c}function h(a,c){b.J=a;b.f=c===void 0?1:c;return b}function d(a){return a===void 0?1:isNaN(a=+a)||a<0||a===r?e.d():a}var c={},g={},b={},f={},r=1/0;e.Cache=new ovi.Class({initialize:function(a,b,c,f){this.fc=d(a);if(b)this.ie=b;if(c)this.Oe=c;if(f)this.Y=f;this.s={}},Statics:{DONT:c,NEXT:g,NOT_ENOUGH_SPACE:f,change:h},f:0,change:h,add:function(a,e,k){var h=this.ie,p=this.Y,r=this.s,s=r[a],u;if(h){if((h=h(e))===
g)return s&&this.remove(a,1),p?p.add(a,e,k):g;if(h===c)return s&&this.remove(a),c;h===b?(e=h.J,k=h.f):e=h}if((k=d(k))>this.fc)return p?p.add(a,e,k):f;if(s)this.f+=k-s.f,s.J=e,s.f=k,this.gc(s);else{s=r[a]=this.W=new l(a,e,this.W,k);if(!this.ga)this.ga=s;this.f+=k}for(;this.f>this.fc;)this.S((u=this.ga).c,u),p&&p.add(u.c,u.J,u.f)},get:function(a,b){var c=this.s[a],d;c&&(b||this.gc(c));return c?c.J:(d=this.Y)?d.get(a,b):void 0},remove:function(a,b){var c=this.s[a],d,f;c&&this.S(a,c);if(!b&&(d=this.Y))f=
d.remove(a,b);return c?c.J:f},removeAll:function(a){var b=this.s,c,d;for(c in b)b.hasOwnProperty(c)&&!c.indexOf(a)&&this.S(c,b[c]);(d=this.Y)&&d.removeAll(a)},destroy:function(){var a=this.s,b,c;for(c in a)(b=a[c]).X=0,b.Z=0;this.ga=this.W=0;this.Y&&this.Y.destroy()},S:function(a,b,c){var d=b.Z,f=b.X,e;d?f?(d.X=f).Z=d:(this.ga=d).X=void 0:(this.W=f)?f.Z=void 0:this.ga=void 0;if(!c)delete this.s[a],this.f-=b.f,(e=this.Oe)&&e(b.J);return b.J},gc:function(a){var b=this.W;if((b=this.W)!==a){this.S(a.c,
a,1);if(b)(b.Z=a).X=b;(this.W=a).Z=void 0}}});l.prototype.f=1})(nokia.maps.util);ovi.provide("nokia.maps.map.provider.IData");ovi.provide("nokia.maps.map.provider.IObjectProvider");ovi.provide("nokia.maps.kml.ObservableNode");
(function(e){var l=e.util.Coroutine,h=e.kml.ObservableNode=new ovi.Class({Extends:e.util.OObject,initialize:function(d){this.node=d;this.set("state",h.State.INITIAL)},Statics:{State:{INITIAL:"initial",READY:"ready"},vr:0,getParsedNodesCount:function(){return h.vr}},Jj:function(){},Fj:function(d){return new h(d)},Sj:function(d){return d&&d.nodeType==1},Rm:function(d){return(d&&d.childNodes||[]).length===0},em:!1,lv:function(){var d=this.parent;d&&(d.readyCount++,d.em&&d.validCount==d.readyCount&&d.set("state",
h.State.READY))},ot:function(){delete this.readyCount;delete this.validCount;delete this.em;delete this.node},load:function(d,c){var e=this,b=e.node;if(!b||e.state==h.State.READY)e.set("state",h.State.READY);else{if(c)e.parent=c;e.addObserver("state",function(){e.state=="ready"&&(e.ot(),(d||e.lv).apply(e))});e.Jj();h.vr++;e.Rm(b)?e.set("state",h.State.READY):(e.readyCount=0,e.validCount=0,l.create("nokia.maps.kml.ObservableNode#load",function(b){var c;if(!b.has("index"))b.index=0;if(!b.has("childNodes"))b.childNodes=
e.node.childNodes||[];if(!b.has("length"))b.length=b.childNodes.length;for(;b.index<b.length;)if(c=b.childNodes[b.index],e.Sj(c)&&(e.validCount++,c=e.Fj(c,e.validCount-1),c.load(null,e)),b.index++,l.shallYield())return l.yield();e.em=!0;e.validCount==e.readyCount&&e.set("state",h.State.READY)})())}}})})(nokia.maps);ovi.provide("nokia.maps.map.HitArea");
(function(){var e=Math,l=e.PI/180,h=e.ceil,d=e.min,c=e.sin,g=e.cos,b=nokia.maps.util,f=b.Point,r=nokia.maps.map.HitArea=new ovi.Class({initialize:function(a,f){var e=(f=[].concat(f)).length,m=e,p,r,s,u,w;this.values=f;for(this.type=a;m--;)isNaN(f[m]=f[m])&&b.d("Given argument is not the array of numbers");a==="rect"&&e>3&&(f=[+f[0],+f[1],+f[2],+f[1],+f[2],+f[3],+f[0],+f[3]],a="poly");if(a==="circle"&&e>2&&(s=+f[2])>0){p=+f[0];r=+f[1];m=d(h(s)*2,40);u=360/m;for(f=[];m--;)w=u*m*l,f.push(p+c(w)*s,r+
g(w)*s);a="poly"}if(a==="poly"&&e&&!(f.length%2))this.lc=f;!this.lc&&b.d("bad polygon")},Statics:{from:function(a){return a instanceof r?a:new r(a.type,a.values?a.values:a.coords)}},hitTest:function(a,b,c){return f.isCoveredBy(a,b,this.lc,c,!0)}})})();ovi.provide("nokia.maps.map.provider.NullObjectProvider");
(function(e){e.map.provider.NullObjectProvider=new ovi.Class({zg:function(){},si:function(){},Dc:function(){},requestBBox:function(){return[]},cancelBBoxRequest:function(){},adopt:function(e){if(e.e)return!1;e.e=this;return e},orphan:function(e){if(e.e!==this)return!1;e.e=null;return e}})})(nokia.maps);ovi.provide("nokia.maps.kml.DOM");
(function(e){var l=e.geo.Coordinate,h=e.util,d=e.kml.DOM=new ovi.Class({Statics:{getString:function(c){try{for(var d="",b=0,f=c.childNodes,e=f.length;b<e;b+=1)d+=f[b].nodeValue.replace(/^\s+|\s+$/g,"")}catch(a){}return d||""},getAltitudeMode:function(c){c=d.getString(c);return/^clampToGround$|^relativeToGround$|^absolute$/.test(c)?c:"clampToGround"},getBoolean:function(c){return/^1$|^true$/.test(d.getString(c))},getFloat:function(c){return parseFloat(d.getString(c))||0},getInteger:function(c){return parseInt(d.getString(c))||
0},getColor:function(c){c=d.getString(c);return/^[0-9a-fA-F]{8}$/.test(c)?"#"+c.substr(6,2)+c.substr(4,2)+c.substr(2,2)+c.substr(0,2):"#000000ff"},getNodeId:function(c){return d.getNodeAttribute(c,"id")},getNodeAttribute:function(c,d){var b;c[d]?b=c[d]:"getAttribute"in c&&(b=c.getAttribute(d));return b},parseCoords:function(c){var e=c.split(/\s+/),b=e.length,f=!(e&&b==1),h=f?1:3,a=[],l;if(!f)e=c.split(","),b=e.length;for(l=0;l<b;l+=h)if(c=d.parseCoord(f?e[l]:l+3>e.length?null:e.slice(l,l+3)))a.push(c);
else return[];return a},parseCoord:function(c){if(!c)return null;var d=c instanceof Array&&c.length>0&&c.length<4?c:c.split(","),c=parseFloat(d[0]),b=parseFloat(d[1]),d=parseFloat(d[2]);return isNaN(b)||isNaN(c)?null:new l(b,c,isNaN(d)?void 0:d)},parseFromString:function(c){return h.Uf(c)},isValidNode:function(c,d){return!!c&&!!d&&function(b,c){if(Array.prototype.indexOf)return b.indexOf(d);else{for(var e=0,a=b.length;e<a;e++)if(b[e].toLowerCase()===c.toLowerCase())return e;return-1}}(c,d)!=-1}}})})(nokia.maps);
ovi.provide("nokia.maps.kml.Vector2");(function(e){var l=e.DOM;e.Vector2=new ovi.Class({initialize:function(e){this.x=l.getNodeAttribute(e,"x");this.y=l.getNodeAttribute(e,"y");this.xunits=l.getNodeAttribute(e,"xunits");this.yunits=l.getNodeAttribute(e,"yunits")}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.Object");(function(e){var l=e.DOM;e.Object=new ovi.Class({initialize:function(e){this.id=e&&l.getNodeId(e);this.node=e}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.StyleSelector");
(function(e){e.StyleSelector=new ovi.Class({Extends:e.Object,initialize:function(e){this._super(e)}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.ColorStyle");
(function(e){var l=e.kml,h=l.DOM,d=e.util.ColorHelper;l.ColorStyle=new ovi.Class({Extends:l.Object,initialize:function(c){var e=c.childNodes,b;this._super(c);for(c=e.length;c--;)switch(b=e[c],b.nodeName){case "color":this.color=h.getColor(b);break;case "colorMode":this.colorMode=h.getString(b)}if(this.color&&this.colorMode=="random")this.color="#"+d.toRandomRGBA(this.color)}})})(nokia.maps);ovi.provide("nokia.maps.kml.Link");
(function(e){var l=e.DOM;e.Link=new ovi.Class({Extends:e.Object,initialize:function(e){var d=e.childNodes,c=d.length;for(this._super(e);c--;)if(e=d[c],e.nodeName=="href"){this.href=l.getString(e);break}},href:""})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.LabelStyle");(function(e){var l=e.DOM;e.LabelStyle=new ovi.Class({Extends:e.ColorStyle,initialize:function(e){var d=e.childNodes,c;this._super(e);for(e=d.length;e--;)switch(c=d[e],c.nodeName){case "scale":this.scale=l.getFloat(c)}}})})(nokia.maps.kml);
ovi.provide("nokia.maps.kml.LineStyle");(function(e){var l=nokia.maps.kml.DOM;e.LineStyle=new ovi.Class({Extends:e.ColorStyle,initialize:function(e){var d=e.childNodes,c;this._super(e);for(e=d.length;e--;)switch(c=d[e],c.nodeName){case "width":this.width=l.getFloat(c)}},Statics:{DEFAULT_STROKE_COLOR:"#000000ff",DEFAULT_STROKE_WIDTH:1}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.PolyStyle");
(function(e){var l=e.DOM;e.PolyStyle=new ovi.Class({Extends:e.ColorStyle,initialize:function(e){var d=e.childNodes,c;this._super(e);this.outline=this.fill=!0;for(e=d.length;e--;)switch(c=d[e],c.nodeName){case "fill":this.fill=l.getBoolean(c);break;case "outline":this.outline=l.getBoolean(c)}}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.BalloonStyle");
(function(e){var l=e.DOM;e.BalloonStyle=new ovi.Class({Extends:e.Object,initialize:function(e){var d,c;if(e){d=e.childNodes;this._super(e);for(e=d.length;e--;)switch(c=d[e],c.nodeName){case "bgColor":this.bgColor=l.getColor(c);break;case "textColor":this.textColor=l.getColor(c);break;case "text":this.text=l.getString(c);break;case "displayMode":this.displayMode=l.getString(c)}}},text:"",displayMode:"default"})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.Geometry");
(function(e){var l=e.kml,h=e.util;l.Geometry=new ovi.Class({Mixins:[l.ObservableNode],Extends:l.Object,initialize:function(d){this._super(d)},weight:0,Rm:function(){return!0},getCenterCoordinate:function(){h.Lo("Can't calculate center coordinate on abstract object")},getStyle:function(){h.Lo("Can't get style of an abstract object")}})})(nokia.maps);ovi.provide("nokia.maps.kml.LineString");
(function(e){var l=e.kml,h=l.DOM,d=e.geo.Coordinate;l.LineString=new ovi.Class({Extends:l.Geometry,initialize:function(c,d,b){var f=c.childNodes;this._super(c);this.lineStyle=d;this.balloonStyle=b;for(c=f.length;c--;)switch(d=f[c],d.nodeName){case "extrude":this.extrude=h.getBoolean(d);break;case "altitudeMode":this.altitudeMode=h.getAltitudeMode(d);break;case "tessellate":this.tessellate=h.getBoolean(d);break;case "coordinates":this.coordinates=this.In(h.getString(d))}this.weight=this.coordinates.length},
coordinates:[],In:function(c){var d=[];try{d=h.parseCoords(c)}catch(b){d=[]}if(d.length<2)return[];return d},getCenterCoordinate:function(){var c=this.coordinates,e=c.length-1,b=0,f=0;if(c){for(;e--;)b+=c[e].latitude,f+=c[e].longitude;return new d(b/c.length,f/c.length)}},getStyle:function(){var c,d={};d.color=this.color=l.LineStyle.DEFAULT_STROKE_COLOR;d.width=this.width=l.LineStyle.DEFAULT_STROKE_WIDTH;if(this.lineStyle){if(this.lineStyle.color)d.color=this.color=this.lineStyle.color;if(this.lineStyle.width)d.width=
this.width=this.lineStyle.width}if(c=this.balloonStyle){if(c.bgColor)d.bgColor=this.bgColor=c.bgColor;if(c.textColor)d.textColor=this.textColor=c.textColor;if(c.text)d.text=this.text=c.text;if(c.displayMode)d.displayMode=this.displayMode=c.displayMode}return d}})})(nokia.maps);ovi.provide("nokia.maps.kml.LinearRing");
(function(e){var l=e.kml,h=l.DOM,d=e.geo.Coordinate;l.LinearRing=new ovi.Class({Extends:l.Geometry,initialize:function(c,d,b){var f=c.childNodes;this._super(c);this.lineStyle=d;this.balloonStyle=b;for(c=f.length;c--;)switch(d=f[c],d.nodeName){case "extrude":this.extrude=h.getBoolean(d);break;case "altitudeMode":this.altitudeMode=h.getAltitudeMode(d);break;case "tessellate":this.tessellate=h.getBoolean(d);break;case "coordinates":this.coordinates=this.In(h.getString(d))}this.weight=this.coordinates.length},
coordinates:[],In:function(c){var d=[];try{d=h.parseCoords(c)}catch(b){d=[]}if((c=d.length)<2)return[];d[0].equals(d[c-1])||d.push(d[0]);return d},getCenterCoordinate:function(){var c=this.coordinates,e=c.length-1,b=0,f=0;if(c){for(;e--;)b+=c[e].latitude,f+=c[e].longitude;return new d(b/(c.length-1),f/(c.length-1))}return null},getStyle:function(){var c,d={};d.color=this.color=l.LineStyle.DEFAULT_STROKE_COLOR;d.width=this.width=l.LineStyle.DEFAULT_STROKE_WIDTH;if(this.lineStyle){if(this.lineStyle.color)d.color=
this.color=this.lineStyle.color;if(this.lineStyle.width)d.width=this.width=this.lineStyle.width}if(c=this.balloonStyle){if(c.bgColor)d.bgColor=this.bgColor=c.bgColor;if(c.textColor)d.textColor=this.textColor=c.textColor;if(c.text)d.text=this.text=c.text;if(c.displayMode)d.displayMode=this.displayMode=c.displayMode}return d}})})(nokia.maps);ovi.provide("nokia.maps.kml.Icon");
(function(e){var l=e.DOM;e.Icon=new ovi.Class({Extends:e.Link,initialize:function(e){var d=e.childNodes,c;this._super(e);this.offsetX=this.offsetY=0;for(e=d.length;e--;)switch(c=d[e],c.nodeName){case "gx:x":this.offsetX=l.getInteger(c);break;case "gx:y":this.offsetY=l.getInteger(c)}}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.Point");
(function(e){var e=e.kml,l=e.DOM;e.Point=new ovi.Class({Extends:e.Geometry,initialize:function(e,d,c,g){var b=e.childNodes,f;this._super(e);this.iconStyle=d;this.iconStyleHighlighted=c;this.balloonStyle=g;for(e=b.length;e--;)switch(d=b[e],d.nodeName){case "extrude":this.extrude=l.getBoolean(d);break;case "altitudeMode":this.altitudeMode=l.getAltitudeMode(d);break;case "coordinates":f=l.getString(d)}if(f)this.coordinate=l.parseCoord(f)||void 0},weight:1,coordinate:void 0,getCenterCoordinate:function(){return this.coordinate},
getStyle:function(){var e,d={};if(this.iconStyle){if(this.iconStyle.color)d.brush=this.brush=this.iconStyle.color;if(this.iconStyle.scale)d.scale=this.scale=this.iconStyle.scale;if(this.iconStyle.hotSpot)d.offsetX=this.offsetX=this.iconStyle.hotSpot.x,d.offsetY=this.offsetY=this.iconStyle.hotSpot.y,d.offsetXUnits=this.offsetXUnits=this.iconStyle.hotSpot.xunits,d.offsetYUnits=this.offsetYUnits=this.iconStyle.hotSpot.yunits;if(this.iconStyle.icon&&this.iconStyle.icon.href)d.icon=this.icon=this.iconStyle.icon.href}if(this.iconStyleHighlighted){if(this.iconStyleHighlighted.color)d.brushHighlighted=
this.brushHighlighted=this.iconStyleHighlighted.color;if(this.iconStyleHighlighted.scale)d.scaleHighlighted=this.scaleHighlighted=this.iconStyleHighlighted.scale;if(this.iconStyleHighlighted.hotSpot)d.offsetXHighlighted=this.offsetXHighlighted=this.iconStyleHighlighted.hotSpot.x,d.offsetYHighlighted=this.offsetYHighlighted=this.iconStyleHighlighted.hotSpot.y,d.offsetXHighlightedUnits=this.offsetXHighlightedUnits=this.iconStyleHighlighted.hotSpot.xunits,d.offsetYHighlightedUnits=this.offsetYHighlightedUnits=
this.iconStyleHighlighted.hotSpot.yunits;if(this.iconStyleHighlighted.icon&&this.iconStyleHighlighted.icon.href)d.iconHighlighted=this.iconHighlighted=this.iconStyleHighlighted.icon.href}if(e=this.balloonStyle){if(e.bgColor)d.bgColor=this.bgColor=e.bgColor;if(e.textColor)d.textColor=this.textColor=e.textColor;if(e.text)d.text=this.text=e.text;if(e.displayMode)d.displayMode=this.displayMode=e.displayMode}return d}})})(nokia.maps);ovi.provide("nokia.maps.map.Object");
(function(e){if(!e.util.getConstructor(e.map.Object)){var l=0,h=0,d=function(c,b){var d=c.Ua(),e=b.Ua(),a,l,k,m=0,p;if(!d||!e)return 0;a=d.length;l=e.length;for(k=a<l?a:l;m<k;m++)if(p=e[m]-d[m])return h?-p:p;return h?a-l:l-a},c={rev:0,sort:function(c,b,f){var e=[],a,l,k=c.length;for(l=0;l<k;l++)((a=c[l]).getIconForRendering||a.drawToTile)&&(b||a.isVisible())&&e.push(a);h=f;e.sort(d);return e},create:function(c){var b=c.t,d;d=null;b&&(d=(d=b.Ua())?d.slice():[],d.push(c.zIndex,b.objects.indexOf(c)));
return d}};nokia.maps.map.Object=new ovi.Class({Extends:e.util.OObject,Mixins:e.dom.EventTarget,Statics:{sortByZInfo:c.sort,CHANGE_SPATIAL:1,CHANGE_VISUAL:2,CHANGE_ZINDEX:4},dispatch:function(c){c.display=this.getDisplay();return e.dom.EventTarget.prototype.dispatch.call(this,c)},initialize:function(c){this.e=new e.map.provider.NullObjectProvider;this.id=l++;c&&"draggable"in c?(c.isDraggable=c.draggable,delete c.draggable,this._super(c),c.draggable=c.isDraggable,delete c.isDraggable):this._super(c);
this.addObserver("*",this.nc,this)},t:null,CHANGE_SPATIAL:1,CHANGE_VISUAL:2,CHANGE_ZINDEX:4,isEventTarget:!0,zIndex:0,visibility:!0,B:"object",ad:function(){return this.ac||(this.ac={})},destroy:function(){var c=this.t;c&&c.objects.remove(this);this.removeAllListeners();this.e=null;this.removeObserver("*",this.nc,this)},getInvalidations:function(c){var b=this.ac;return b?(b[1]>c)*1|(b[2]>c)*2|(b[4]>c)*4:0},nc:function(c,b){this.ja(b,0)},getProvider:function(){return this.e},getParent:function(){return this.t},
getRoot:function(){for(var c=this,b;b=c.t;)c=b;return c},getDisplay:function(){var c=this.getRoot();return c.B==="display"?c:null},isVisible:function(){var c=this,b=!1;do b=c.visibility;while(b&&(c=c.t));return b},ja:function(c,b){var d;d=this.e;var e;b|=c==="zIndex"?4:c==="visibility"?2:0;e=d.Dc(this,b);d=this.ad();b&1&&(d[1]=e);b&2&&(d[2]=e);b&4&&(d[4]=e)},zIndexSetter:function(c){this.bc();return c},eventListenerSetter:function(c){var b=0,d,e;if(c)for(e in this.removeAllListeners(),c)if((b=ovi.type(d=
c[e]))==="array")for(b=0;b<d.length;b+=3)this.addListenerNS(d[b+2],e,d[b],d[b+1]);else b==="function"&&this.addListenerNS(null,e,d,!1)},Ua:function(){var d;if(!(d=this.Bc))d=this.Bc=c.create(this);return d},bc:function(){this.Bc=void 0},adopt:function(c){return c.adopt(this)},orphan:function(){return this.e.orphan(this)}})}})(nokia.maps);ovi.provide("nokia.maps.kml.IconStyle");
(function(e){var l=e.DOM,h=e.Icon,d=e.Vector2;e.IconStyle=new ovi.Class({Extends:e.ColorStyle,initialize:function(c){if(c){var e=c.childNodes,b;this._super(c);for(c=e.length;c--;)switch(b=e[c],b.nodeName){case "scale":this.scale=l.getFloat(b);break;case "heading":this.heading=l.getFloat(b);break;case "Icon":if(b=new h(b))this.icon=b;break;case "hotSpot":this.hotSpot=new d(b)}}}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.Style");
(function(e){var l=e.IconStyle,h=e.LabelStyle,d=e.LineStyle,c=e.PolyStyle,g=e.BalloonStyle;e.Style=new ovi.Class({Extends:e.StyleSelector,initialize:function(b){var f=b.childNodes,e;this._super(b);for(b=f.length;b--;)switch(e=f[b],e.nodeName){case "IconStyle":if(e=new l(e))this.iconStyle=e;break;case "LabelStyle":if(e=new h(e))this.labelStyle=e;break;case "LineStyle":if(e=new d(e))this.lineStyle=e;break;case "PolyStyle":if(e=new c(e))this.polyStyle=e;break;case "BalloonStyle":if(e=new g(e))this.balloonStyle=
e}},getStyle:function(){return this}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.Pair");
(function(e){var l=e.DOM,h=e.Style;e.Pair=new ovi.Class({Extends:e.Object,initialize:function(d,c){var e=d.childNodes,b,f;this._super(d);this.styleContainer=c;for(f=e.length;f--;)switch(b=e[f],b.nodeName){case "key":this.key=l.getString(b);break;case "styleUrl":this.styleUrl=l.getString(b);break;case "Style":if(b=new h(b))this.style=b}},getStyle:function(){if(this.style)return this.style;if(this.styleUrl)return this.styleContainer.getStyleById(this.styleUrl.substr(1));return null}})})(nokia.maps.kml);
ovi.provide("nokia.maps.kml.FeatureStyle");
(function(e){function l(d,b,f){return f?c(d,b,!1):c(b,d,!1)}var h=e.kml,d=h.Style,c=e.util.proto;h.FeatureStyle=new ovi.Class({initialize:function(c,b){this.mergeStyle(c,b)},mergeStyle:function(c,b,f){var e,a;if(c){e=c.iconStyle;a=c.iconStyleHighlighted;if(b&&c instanceof d){if(e)this.iconStyleHighlighted=l(this.iconStyle,e,f)}else if(this.iconStyle=l(this.iconStyle,e,f),a)this.iconStyleHighlighted=l(this.iconStyleHighlighted,a,f);if(c.balloonStyle)this.balloonStyle=l(this.balloonStyle,c.balloonStyle,
f);if(c.labelStyle)this.labelStyle=l(this.labelStyle,c.labelStyle,f);if(c.lineStyle)this.lineStyle=l(this.lineStyle,c.lineStyle,f);if(c.polyStyle)this.polyStyle=l(this.polyStyle,c.polyStyle,f)}}})})(nokia.maps);ovi.provide("nokia.maps.kml.StyleContainer");
(function(e){var l=e.Style;e.StyleContainer=new ovi.Class({initialize:function(e){this.styles={};e&&e.id&&(this.styles[e.id]=e)},push:function(e){e&&e.id&&(this.styles[e.id]=e);return this.styles},getStyleById:function(e,d){var c=this.styles[e];if(!c)return null;if(c instanceof l&&d)return null;return c.getStyle(d)},getStyles:function(){return this.styles}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.Polygon");
(function(e){var l=e.kml,h=l.DOM,d=l.LinearRing,c=l.LineStyle,g=l.FeatureStyle,b=e.geo.Coordinate;l.Polygon=new ovi.Class({Extends:l.Geometry,initialize:function(b,c,a,e){var k=b.childNodes,m,p=0,l=k.length;m=0;this._super(b);if(c&&e)e.polyStyle=c;if(a&&e)e.balloonStyle=a;this.featureStyle=e||new g;for(this.innerBoundaryIs=[];p<l;){m=k[p];switch(m.nodeName){case "extrude":this.extrude=h.getBoolean(m);break;case "altitudeMode":this.altitudeMode=h.getAltitudeMode(m);break;case "tessellate":this.tessellate=
h.getBoolean(m);break;case "outerBoundaryIs":c=m.childNodes;b=0;for(m=c.length;b<m;){if(c[b].nodeName=="LinearRing")this.outerBoundaryIs=new d(c[b]),this.weight+=this.outerBoundaryIs.weight;b++}break;case "innerBoundaryIs":c=m.childNodes;b=0;for(m=c.length;b<m;)a=c[b],a.nodeName=="LinearRing"&&(this.innerBoundaryIs.push(a=new d(a)),this.weight+=a.weight),b++}p++}},getPathOuter:function(){if(this.pathOuter===void 0&&(this.pathOuter=null,this.outerBoundaryIs&&this.outerBoundaryIs.constructor===d))this.pathOuter=
this.outerBoundaryIs.coordinates;return this.pathOuter},getCenterCoordinate:function(){var c=this.getPathOuter(),d=c.length-1,a=d,e=0,g=0;if(c){for(;d--;)e+=c[d].latitude,g+=c[d].longitude;return new b(e/a,g/a)}return null},getStyle:function(){var b=this.featureStyle.balloonStyle,d=this.featureStyle.polyStyle,a=this.featureStyle.lineStyle,e={};e.color=this.color="#ff00007d";e.fillColor=this.fillColor="#0000ff7d";e.width=this.width=c.DEFAULT_STROKE_WIDTH;e.strokeColor=c.DEFAULT_STROKE_COLOR;if(d){if(d.color)e.fillColor=
this.fillColor=d.color;if(!d.fill)e.fillColor=this.fillColor="#00000000";if(!d.outline)e.width=this.width=0}if(a&&(e.strokeColor=a.color||c.DEFAULT_STROKE_COLOR,d&&d.outline))e.width=a.width||c.DEFAULT_STROKE_WIDTH;if(b){if(b.bgColor)e.bgColor=this.bgColor=b.bgColor;if(b.textColor)e.textColor=this.textColor=b.textColor;if(b.text)e.text=this.text=b.text;if(b.displayMode)e.displayMode=this.displayMode=b.displayMode}return e}})})(nokia.maps);ovi.provide("nokia.maps.kml.MultiGeometry");
(function(e){var e=e.kml,l=e.DOM,h=e.Point,d=e.LineString,c=e.LinearRing,g=e.Polygon,b=e.MultiGeometry=new ovi.Class({Extends:e.Geometry,initialize:function(b,c,a,d){this.featureStyle=c;this.placemark=d;this._super(b)},Jj:function(){this.geometries=[]},Sj:function(b){return l.isValidNode(["Point","LineString","LinearRing","Polygon","MultiGeometry"],b.nodeName)},Rm:function(){return!1},Fj:function(f){var e=this.featureStyle,a=this.placemark,l;switch(f.nodeName){case "Point":l=new h(f,e.iconStyle,e.iconStyleHighlighted,
e.balloonStyle);break;case "LineString":l=new d(f,e.lineStyle,e.balloonStyle);break;case "LinearRing":l=new c(f,e.lineStyle,e.balloonStyle);break;case "Polygon":l=new g(f,null,null,e);break;case "MultiGeometry":l=new b(f,e,e.balloonStyle,a)}l&&(this.weight+=l.weight,this.geometries.push(this.yu(l,a)));return l},yu:function(b,c){if(b&&c)b.visibility=c.visibility,b.name=c.name,b.description=c.description;return b}})})(nokia.maps);ovi.provide("nokia.maps.map._MarkerIcon");
(function(){function e(c){return new b(typeof c==="object"?c.strokeColor?{strokeColor:a(c.strokeColor)}:void 0:{strokeColor:c})}var l=nokia.maps,h=l.map.HitArea,d=l.util,c=d.proto,g=d.Point,b=d.Pen,f=new b({strokeColor:"#FFF"}),r=d.Brush,a=d.ColorHelper.getHex3,q=l.gfx,k=q.GraphicsImage,m=q.IDL,p=q.Color.parseCss,z=[4207599104,4207599105,4207599106,"$Text$"],s=new l.gfx.SvgParser,u=d.pd("shape text textPen pen brush effect"),w=d.flatMerge(d.pd("anchor hitArea"),u),x=new d.Cache(50),v=nokia.maps.map.Sb=
new ovi.Class({Extends:nokia.maps.util.OObject,initialize:function(a){var b;a&&a.shape&&a.shape!==this.shape?(this.shape=this.shapeSetter(b=a.shape),delete a.shape,this._super(a),a.shape=b):(this.shapeSetter(this.shape),this._super(a));this.addObserver("*",this.we)},Statics:{Qn:w,$a:function(a){return a in w},Le:function(a){return!(a in u)},rc:{balloon:['<path style="opacity:0.4;fill:#353535" d="m 19,31 c 0,1.67 -2.69,3 -6,3 c -3.31,0 -6,-1.33 -6,-3 c 0,-1.67 2.69,-3 6,-3 c 3.31,0 6,1.33 6,3 z" /><path style="fill:#Facade01" d="m 13,0 c -3.47,0 -6.73,1.32 -9.19,3.75 C 1.36,7.82 0,9.41 0,12.84 c 0,3.43 1.36,6.64 3.81,9.06 L 13,31 l 9.19,-9.094 c 2.46,-2.43 3.81,-5.63 3.81,-9.06 c 0,-3.43 -1.36,-6.67 -3.81,-9.09 C 19.73,1.32 16.47,0 13,0 z"/><path style="fill:#ffffff" d="m 13,1 c -3.21,0 -6.23,1.23 -8.5,3.47 c -2.26,2.24 -3.5,5.22 -3.5,8.38 c 0,3.16 1.24,6.14 3.5,8.38 l 8.5,8.38 l 8.5,-8.38 c 2.26,-2.24 3.5,-5.22 3.5,-8.38 c 0,-3.16 -1.24,-6.14 -3.5,-8.38 C 19.23,2.23 16.2,1 13,1 z"/><path style="fill:#Facade00;fill-opacity:1" d="m 13,2.19 c -7,0 -10.74,4.96 -10.81,10.65 c 0,3.27 0.95,5.61 3.03,7.66 l 7.79,7.69 l 7.79,-7.69 c 2.07,-2.05 3.02,-4.27 3.03,-7.66 C 23.58,7.07 19.98,2.19 13,2.19 z"/><text x="13" y="18" font-size="10pt" font-family="arial" font-weight="bold" text-anchor="middle" fill="#Facade02">$Text$</text>',
28,36,13,31,"poly",[0,16,0,7,8,0,18,0,26,7,26,16,18,34,8,34]]}},text:"",pen:c({},f),textPen:c({},f),brush:c({},new r({color:"#1080DD"})),shape:"balloon",effect:"none",we:function(a,b){if(b in u)a.c="",a.Va=0},shapeSetter:function(a){var b=v.rc[a]||d.d("shape");this.f=new g(b[1],b[2]);this.anchor=new g(b[3],b[4]);this.hitArea=b[5]?new h(b[5],b[6]):void 0;return a},brushSetter:function(b){return new r(typeof b==="object"?b.color?{color:a(b.color)}:void 0:{color:b})},penSetter:e,textPenSetter:e,textSetter:function(a){return d.sanitizeText(a)},
ue:function(){var a=v.rc[this.shape],b,c,d,f;if(a&&typeof a[0]==="string"){b=z.length;for(c=a[0]=ovi.Array(s.parseSvg('<svg version="1.1" width="'+(d=a[1])+'" height="'+(f=a[2])+'" viewBox="0 0 '+d+" "+f+'">'+a[0]+"</svg>").data);b--;){f=[];for(d=-1;(d=c.indexOf(z[b],d+1))!==-1;)f.push(d);f.length&&(a[7+b]=f)}}return a},bf:function(a){for(var b=[p(this.brush.color,1),p(this.pen.strokeColor,1),p(this.textPen.strokeColor,1),this.text],c=b.length,d=a[0].slice(),f,e;c--;)if(f=a[7+c])for(e=f.length;e--;)d[f[e]]=
b[c];return d},getIcon:function(){var a,b;if(!this.Va){if(!(b=x.get(a=this.fa())))x.add(a,b=new k(new m(this.bf(this.ue()))));this.Va=b}return this.Va},fa:function(){return this.c||(this.c=(this.hasOwnProperty("shape")?this.shape:"").concat(this.text,this.textPen.fa(),"P",this.pen.fa(),"B",this.brush.fa()))}})})();ovi.provide("nokia.maps.kml.StyleMap");
(function(e){var l=nokia.maps.kml.Pair;e.StyleMap=new ovi.Class({Extends:e.StyleSelector,initialize:function(e,d){var c=e.childNodes,g,b;this._super(e);this.styleContainer=d;this.pairs=[];for(b=c.length;b--;)switch(g=c[b],g.nodeName){case "Pair":(g=new l(g,this.styleContainer))&&this.pairs.push(g)}},getStyle:function(e){var d=null,c="normal";e&&(c="highlight");for(e=0;e<this.pairs.length;e++)if(this.pairs[e].key==c){d=this.pairs[e].getStyle();break}return d}})})(nokia.maps.kml);ovi.provide("nokia.maps.map.Marker");
(function(){var e=nokia.maps,l=e.util,h=e.dom,d=e.map,c=e.gfx,g=l.Point,b=l.Strip,f=new g(0,0),r=l.Rectangle,a=d.Sb,q=e.geo,k=d.HitArea,m=q.Coordinate,e=new ovi.Class({Extends:d.Object,initialize:function(b,c){var d;if(this.B==="marker"&&(!c||!("icon"in c)))d=new a,this.set("icon",d.getIcon()),this.set("anchor",d.anchor),this.set("hitArea",d.hitArea);this.Xa={};this._super(c);this.set("coordinate",b,1)},B:"marker",anchor:f,f:f,coordinateSetter:function(a){(a=m.fromObject(a))||l.d("coord");this.Xa=
{};return a},hitAreaSetter:function(a){return!a?a:k.from(a)},anchorSetter:function(a){(a=g.fromObject(a))||l.d("you have to set util.Point");return a},draggableSetter:function(a){return this.isDraggable=a},Qa:function(a){this.f=new g(a.width,a.height);this.sc=1},iconSetter:function(a){ovi.type(a);a instanceof c.Image||(a=c.Image.fromObject(a));a instanceof c.Image||l.d("icon");this.icon=a.F===document?a:a.clone(document);a.state===1?this.Qa(a):this.sc=0;return this.icon},getBoundingBox:function(){return q.BoundingBox.coverAll([this.coordinate])},
getDisplayBoundingBox:function(a){a=a.geoToPixel(this.coordinate).sub(this.anchor);return new r([a,a.add(this.f)])},hitTest:function(a,b,c,d){var a=this.getDisplayBoundingBox(a),f=new g(b,c),e=this.hitArea;return a.contains(f)&&(!e||e.hitTest(b-a.topLeft.x,c-a.topLeft.y,d))},getDisplayOffset:function(a,b,c){return(new g(b,c)).sub(a.geoToPixel(this.coordinate))},ja:function(a,b){a!=="zIndex"&&(b|=a==="coordinate"?1:2);this._super(a,b)},xe:function(a){var b="error";a.state===1&&(this.Qa(a),this.ja("icon",
2),b="load");this.dispatch(new h.Event({type:b,target:this,relatedTarget:a}))},getIconForRendering:function(a){var b=this.icon;a!==document&&(b=b.clone(a));b.state?this.sc||b.state===1&&this.Qa(b):b.prepare(this.xe,this);return b},project:function(a){return this.Xa[a.id]||(this.Xa[a.id]=a.geoToMapPoints(b.stencil(b.LAT_LNG,[this.coordinate.latitude,this.coordinate.longitude])))}});if(d.Marker.isNs)d.Marker=e})();ovi.provide("nokia.maps.map.StandardMarker");
(function(){function e(c,d,b){c.V.set(d,b);if(d==="shape")c.f=c.V.f,c.set("anchor",c.V.anchor),c.set("hitArea",c.V.hitArea);return c.V[d]}var l=nokia.maps,h=l.util,d=l.map.Sb,l=nokia.maps.map.StandardMarker=new ovi.Class({Extends:nokia.maps.map.Marker,initialize:function(c,e){var b=this.V=new d(h.flatMerge({},e,1,d.$a));h.flatMerge(this,b,1,d.$a);this.f=b.f;this._super(c,h.flatMerge({},e,1,d.Le))},B:"standardmarker",shapeSetter:function(c){return e(this,"shape",c)},textSetter:function(c){return e(this,
"text",c)},textPenSetter:function(c){return e(this,"textPen",c)},penSetter:function(c){return e(this,"pen",c)},brushSetter:function(c){return e(this,"brush",c)},getIconForRendering:function(c){this.set("icon",this.V.getIcon());return this._super(c)}});h.flatMerge(l.prototype,d.prototype,!0,d.$a)})();ovi.provide("nokia.maps.kml.Feature");
(function(e){var l=e.DOM,h=e.Style,d=e.FeatureStyle,c=e.StyleContainer;e.Feature=new ovi.Class({Mixins:[e.ObservableNode],Extends:e.Object,initialize:function(e,b,f){this._super(e);this.featureStyle=new d(f);this.styleContainer=b||new c},Jj:function(){var c=this.node!=void 0&&this.node.childNodes||[],b,d=this.node!=void 0&&this.node.nodeName,e;this.visibility=!0;for(e=c.length;e--;)switch(b=c[e],b.nodeName){case "name":this.name=l.getString(b);break;case "description":this.description=l.getString(b);
break;case "visibility":this.visibility=l.getBoolean(b);break;case "open":this.open=l.getBoolean(b);break;case "styleUrl":if(this.styleUrl=l.getString(b))b=this.styleUrl.substr(1),this.featureStyle.mergeStyle(this.styleContainer.getStyleById(b),!1,!0),this.featureStyle.mergeStyle(this.styleContainer.getStyleById(b,!0),!0,!0);break;case "Style":(b=new h(b))&&(l.isValidNode(["kml","Folder","Document"],d)||this.featureStyle.mergeStyle(b))}}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.Placemark");
(function(e){var l=e.Point,h=e.DOM,d=e.LineString,c=e.LinearRing,g=e.Polygon,b=e.MultiGeometry;e.Placemark=new ovi.Class({Extends:e.Feature,initialize:function(b,c,a){this._super(b,c,a)},Fj:function(f){var e=this.featureStyle;switch(f.nodeName){case "Point":this.geometry=new l(f,e.iconStyle,e.iconStyleHighlighted,e.balloonStyle);break;case "LineString":this.geometry=new d(f,e.lineStyle,e.balloonStyle);break;case "LinearRing":this.geometry=new c(f,e.lineStyle,e.balloonStyle);break;case "Polygon":this.geometry=
new g(f,null,null,e);break;case "MultiGeometry":this.geometry=new b(f,e,e.balloonStyle,this)}if(this.geometry)this.geometry.visibility=this.visibility,this.geometry.name=this.name,this.geometry.description=this.description,this.geometry.index=this.index,this.geometry.open=this.open;return this.geometry},Sj:function(b){return h.isValidNode(["Point","LineString","LinearRing","Polygon","MultiGeometry"],b.nodeName)}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.component.KMLResultSet");
(function(e){var l=e.util,h=e.kml,d=e.util.Coroutine,c=e.map,g=c.Marker,b=c.StandardMarker,f=/^(?:https?)|(?:file):\/\//,r=e.dom.Page.browser.touch?"tap":"click",a=h.component.KMLResultSet=new ovi.Class({Extends:e.util.OObject,initialize:function(b,d){var f=this,e=b.path||"",h=e.lastIndexOf("/");f.Vf=e.slice(0,h!==-1?h:0)+"/";f.set("state",a.State.INITIAL);f.infoBubble=d&&d.getComponentById("InfoBubbles");f.Bq=b.kmlDocument||b;f.container=new c.Container;f.addObserver("state",function(){f.state==
a.State.FINISHED&&(f.container.addListener("mouseenter",function(a){if(a.target&&a.target instanceof g)a=a.target,a.iconNormal&&a.iconHighlighted&&a.set("icon",a.iconHighlighted)}),f.container.addListener("mouseleave",function(a){var b;(b=a.target)&&b instanceof g&&b.iconNormal&&b.iconHighlighted&&b.set("icon",b.iconNormal)}))})},Statics:{State:{INITIAL:"initial",STARTED:"started",FINISHED:"finished"}},container:null,create:function(){var b=this;if(b.state==a.State.STARTED||b.state==a.State.FINISHED)return b.container;
b.set("state",a.State.STARTED);d.create("nokia.maps.kml.KMLResultSet#create_BFS",function(a){var f,e,g,l,r;l=g=!1;if(!a.has("index"))a.index=0;if(!a.has("weight"))a.weight=0;for(;a.queue.length>0;){f=a.has("queueNode")?a.queueNode:a.queueNode=a.queue.shift();e=f.node;f=f.parent;f=f.objects;g=e instanceof h.Document||e instanceof h.Folder;l=e.geometry&&e.geometry instanceof h.MultiGeometry;if(g||l){e=g?e:e.geometry;r=g?e.features:e.geometries;l=r.length;g=a.has("mapObject")?a.mapObject:new c.Container([],
{visibility:e.visibility});for(a.index===0&&f.add(g);a.index<l;)if(a.queue.push({node:r[a.index],parent:g}),a.index++,d.shallYield())return a.mapObject=g,d.yield();else if(a.index%100===0)return a.mapObject=g,d.sleep(1);a.index=0;delete a.mapObject}else e=e.geometry||e,g=null,e instanceof h.Point?g=b.getPointObject(e):e instanceof h.LinearRing?g=b.getLineObject(e):e instanceof h.LineString?g=b.getLineObject(e):e instanceof h.Polygon&&(g=b.getPolygonObject(e)),g&&(f.add(g),b.ou(g,e)),a.weight+=e.weight;
delete a.queueNode;if(d.shallYield())return d.yield();else if(a.weight>=600)return a.weight=0,d.sleep(1)}},"queue")([{node:b.Bq,parent:b.container}]).onTerminated=function(){delete b.Bq;b.set("state",a.State.FINISHED)};return b.container},ou:function(a,b){var c=this,d=b.getStyle(),f=b.balloonStyle||!!b.featureStyle&&b.featureStyle.balloonStyle;b.displayMode&&b.displayMode=="hide"||a.addListener(r,function(){var e=f&&f.text||"",g=b.name||"",h=b.description||"";if(e)e=e.replace(/\$\[name\]/g,g).replace(/\$\[description\]/g,
h).replace(/\$\[[\w]+\]/g,"");else if(g||h)e+=g?g+"<br / >":"",e+=h;else if(d.text)e=d.text;if(e&&c.infoBubble&&c.infoBubble.openBubble)a.infoBubbleHandler=c.infoBubble.openBubble(e,b.getCenterCoordinate())})},jw:function(a,b){var c=a.icon,d,f,e,g,h;if(c)e=a.geometry,g=c.width,h=c.height,b?(c=e.offsetXHighlighted,d=e.offsetYHighlighted,f=e.offsetXHighlightedUnits,e=e.offsetYHighlightedUnits):(c=e.offsetX,d=e.offsetY,f=e.offsetXUnits,e=e.offsetYUnits),a.set("anchor",new l.Point((f=="pixels"?c:f=="insetPixels"?
g-c:f=="fraction"?g*c:g*0.5)||0,(e=="pixels"?h-d:e=="insetPixels"?d:e=="fraction"?h-h*d:h*0.5)||0))},getPointObject:function(a){var c=this,d,e=a.getStyle(),h,l={visibility:a.visibility};if(a.coordinate){if(h=e.icon)e=e.iconHighlighted,d=new g(a.coordinate,{icon:f.test(h)?h:c.Vf+h,iconNormal:f.test(h)?h:c.Vf+h,iconHighlighted:f.test(e)?e:e?c.Vf+e:void 0,visibility:a.visibility,geometry:a}),d.addListener("load",function(){c.jw(d)});else{if(e.brush)l.brush={color:e.brush};d=new b(a.coordinate,l)}return d}},
getLineObject:function(a){if(!(a.coordinates.length<2)){var b=a.getStyle();return new e.map.Polyline(a.coordinates,{pen:{strokeColor:b.color,lineWidth:b.width},visibility:a.visibility})}},getPolygonObject:function(a){var b=a.getStyle(),c=a.getPathOuter();if(!(c.length<2))return new e.map.Polygon(c,{pen:{strokeColor:b.strokeColor,lineWidth:b.width},brush:{color:b.fillColor},visibility:a.visibility})}})})(nokia.maps);ovi.provide("nokia.maps.kml.Container");
(function(e){var l=e.DOM,h=e.Placemark;e.Container=new ovi.Class({Extends:e.Feature,initialize:function(d,c,e){this._super(d,c,e)},Jj:function(){this.placemarks=[];this.documents=[];this.folders=[];this.features=[];this._super()},Sj:function(d){return l.isValidNode(["Folder","Document","Placemark"],d.nodeName)},Fj:function(d,c){var g=e.Document,b=e.Folder,f;switch(d.nodeName){case "Placemark":(f=new h(d,this.styleContainer,this.featureStyle))&&this.placemarks.push(f);break;case "Document":(f=new g(d,
this.styleContainer,this.featureStyle))&&this.documents.push(f);break;case "Folder":(f=new b(d,this.styleContainer,this.featureStyle))&&this.folders.push(f)}f&&this.features.push(f);f.index=c;return f}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.Folder");(function(e){e.Folder=new ovi.Class({Extends:e.Container,initialize:function(e,h,d){this._super(e,h,d)}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.Document");
(function(e){e.Document=new ovi.Class({Extends:e.Container,initialize:function(e,h,d){this._super(e,h,d)}})})(nokia.maps.kml);ovi.provide("nokia.maps.kml.Manager");
(function(e){var l=e.kml,h=l.StyleContainer,d=l.Style,c=l.StyleMap,g=l.Document,b=l.DOM,f=e.net.Request,r=l.Manager=new ovi.Class({Extends:e.util.OObject,initialize:function(){this.set("state",r.State.INITIAL);this.Lv=new f(f.XHR);this.kmlDocument=null},Statics:{State:{INITIAL:"initial",STARTED:"started",LOADED:"loaded",FINISHED:"finished",FAILED:"failed"}},parse:function(a){var b=this,f,e,l;b.styles=new h;l=a.getElementsByTagName("Style");for(e=l.length;e--;)(f=new d(l[e]))&&f.id&&b.styles.push(f);
l=a.getElementsByTagName("StyleMap");for(e=l.length;e--;)(f=new c(l[e],b.styles))&&f.id&&b.styles.push(f);b.kmlDocument=new g(a,b.styles);b.kmlDocument.load(function(){b.set("state",r.State.FINISHED)});b.kmlDocument.Vf=b.Vf},parseKML:function(a){this.set("state",r.State.STARTED);typeof a=="undefined"?this.set("state",r.State.FAILED):(this.path=a,this.Lv.send(a,ovi.bind(this,this.jv)))},jv:function(a){this.Vf=a.url;!a.error&&!a.timeout?(this.set("state",r.State.LOADED),a=b.parseFromString(a.response).documentElement,
this.parse(a)):this.set("state",r.State.FAILED)}})})(nokia.maps);ovi.provide("nokia.maps.kml._packaging.package-kml");})();
