(function(){ovi.provide("nokia.maps.util.ColorHelper");
(function(e){function l(a){var b;if(a.charAt(0)==="#")b=f[a.length]?a:null;else if(a.substr(0,3)==="rgb"){b=a.match(/\d+(\.\d+)?/g);var c=b.length;b=c>2&&c<5?["#",d(+b[0]),d(+b[1]),d(+b[2]),c>3?d(+b[3]*255):"ff"].join(""):null}b||e.d("Invalid color definition: "+a);return b}function h(a){return!/^(#|rgb).*/.test(a)}function d(a){return a<16?"0"+g(a).toString(16):g(a).toString(16)}function c(a){a=b(a,16);return(a<<4)+a}var g=Math.round,b=parseInt,f={4:function(a){return["#",a.charAt(1),a.charAt(1),
a.charAt(2),a.charAt(2),a.charAt(3),a.charAt(3),"ff"].join("")},5:function(a){return["#",a.charAt(1),a.charAt(1),a.charAt(2),a.charAt(2),a.charAt(3),a.charAt(3),a.charAt(4),a.charAt(4)].join("")},7:function(a){return a+"ff"},9:function(a){return a}},r={4:function(a){return[c(a.charAt(1)),c(a.charAt(2)),c(a.charAt(3)),255]},5:function(a){return[c(a.charAt(1)),c(a.charAt(2)),c(a.charAt(3)),c(a.charAt(4))]},7:function(a){a=b(a.substring(1),16);return[a>>16&255,a>>8&255,a&255,255]},9:function(a){a=b(a.substring(1),
16);return[a>>24&255,a>>16&255,a>>8&255,a&255]}};e.ColorHelper={toInternal:function(a){return h(a)?a:(a=l(a),f[a.length]?f[a.length](a):a)},toRGBA:function(a,b){return h(a)?[0,0,0,255]:(b||(a=l(a)),r[a.length](a))},getHex3:function(a,b){return h(a)?a:(b||(a=l(a),a=f[a.length]?f[a.length](a):a),a.substr(0,7))},getAlpha:function(a,c){return h(a)?1:(c||(a=l(a),a=f[a.length]?f[a.length](a):a),b(a.substr(7,2),16)/255)},toRandomRGBA:function(a,b){if(h(a))return"000000ff";else{for(var a=this.toRGBA(a,b),
c=0;c<4;c++)a[c]=""+d(c<3?Math.floor(Math.random()*(a[c]-0+1))+0:a[c]);return a.join("")}}}})(nokia.maps.util);ovi.provide("nokia.maps.util.Cache");
(function(e){function l(a,b,c,d){this.c=a;this.J=b;if(this.f!==d)this.f=d;if(c)(c.Z=this).X=c}function h(a,c){b.J=a;b.f=c===void 0?1:c;return b}function d(a){return a===void 0?1:isNaN(a=+a)||a<0||a===r?e.d():a}var c={},g={},b={},f={},r=1/0;e.Cache=new ovi.Class({initialize:function(a,b,c,f){this.fc=d(a);if(b)this.ie=b;if(c)this.Oe=c;if(f)this.Y=f;this.s={}},Statics:{DONT:c,NEXT:g,NOT_ENOUGH_SPACE:f,change:h},f:0,change:h,add:function(a,e,k){var m=this.ie,p=this.Y,h=this.s,r=h[a],u;if(m){if((m=m(e))===
g)return r&&this.remove(a,1),p?p.add(a,e,k):g;if(m===c)return r&&this.remove(a),c;m===b?(e=m.J,k=m.f):e=m}if((k=d(k))>this.fc)return p?p.add(a,e,k):f;if(r)this.f+=k-r.f,r.J=e,r.f=k,this.gc(r);else{r=h[a]=this.W=new l(a,e,this.W,k);if(!this.ga)this.ga=r;this.f+=k}for(;this.f>this.fc;)this.S((u=this.ga).c,u),p&&p.add(u.c,u.J,u.f)},get:function(a,b){var c=this.s[a],d;c&&(b||this.gc(c));return c?c.J:(d=this.Y)?d.get(a,b):void 0},remove:function(a,b){var c=this.s[a],d,f;c&&this.S(a,c);if(!b&&(d=this.Y))f=
d.remove(a,b);return c?c.J:f},removeAll:function(a){var b=this.s,c,d;for(c in b)b.hasOwnProperty(c)&&!c.indexOf(a)&&this.S(c,b[c]);(d=this.Y)&&d.removeAll(a)},destroy:function(){var a=this.s,b,c;for(c in a)(b=a[c]).X=0,b.Z=0;this.ga=this.W=0;this.Y&&this.Y.destroy()},S:function(a,b,c){var d=b.Z,f=b.X,g;d?f?(d.X=f).Z=d:(this.ga=d).X=void 0:(this.W=f)?f.Z=void 0:this.ga=void 0;if(!c)delete this.s[a],this.f-=b.f,(g=this.Oe)&&g(b.J);return b.J},gc:function(a){var b=this.W;if((b=this.W)!==a){this.S(a.c,
a,1);if(b)(b.Z=a).X=b;(this.W=a).Z=void 0}}});l.prototype.f=1})(nokia.maps.util);ovi.provide("nokia.maps.map.provider.IData");ovi.provide("nokia.maps.map.provider.IObjectProvider");ovi.provide("nokia.maps.util.proto");
(function(){var e={}.toString,l=nokia.maps.util.proto=function(h,d,c,g){var b=Function(),f,r;b.prototype=d;b=new b;for(f in h)h.hasOwnProperty(f)&&(b[f]=c&&f in d&&e.call(r=h[f])==="[object Object]"?l(r,d[f],c):h[f]);if(c&&!g)for(f in d)if(d.hasOwnProperty(f)&&(r=d[f])===b[f]&&e.call(r)==="[object Object]")b[f]=l(0,r,c);return b}})();ovi.provide("nokia.maps.map.component.zoom.MouseWheel");
(function(e){var l={1:Math.floor,"-1":Math.ceil};e.map.component.zoom.MouseWheel=new ovi.Class({Extends:e.map.component.Component,c:"zoom.MouseWheel",n:"0.0.0.1",initialize:function(){this.vd=ovi.bind(this,this.vd);this.q=this.MAP_2D|this.GLOBE|this.PANORAMA;this._super({enabled:!0})},vd:function(e){var d=e.display,c=d.baseMapType.pType,g=e.timeStamp,b,f;if(this.enabled){b=e.deltaY<0?-1:1;if(c===this.PANORAMA)c=d.getCam(),c.fov+=b,d.setCam(c);else if(g-this.ji>=200)this.ji=g,c=d.getZoom(g=e.displayX,
f=e.displayY),d.setZoomLevel(e.shiftKey?c-b/20:l[b](c-b),"default",g,f);e.cancel()}},ji:0,attach:function(e){this._super(e);e.addListener("wheel",this.vd)},detach:function(e){this._super(e);e.removeListener("wheel",this.vd)}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.DoubleClick");
(function(e){var l=e.map.component;l.zoom.DoubleClick=new ovi.Class({Extends:l.Component,c:"zoom.DoubleClick",n:"0.0.0.1",initialize:function(){function e(b){var a=g.getZoom(b.displayX,b.displayY);if(c.enabled){var d=b.button===2;(f=g.getComponentById("panning.Kinetic"))&&f.set("current",null);g.setZoomLevel(Math[d?"floor":"ceil"](a+(d?-1:1)),"default",b.displayX,b.displayY)}}function d(b){c.enabled&&b.preventDefault()}var c=this,g,b=l.Component.prototype,f;c.q=c.MAP_2D|c.GLOBE;c._super({enabled:!0});
c.attach=function(f){b.attach.call(c,f);g=f;g.addListener("dblclick",e);g.addListener("contextmenu",d)};c.detach=function(f){b.detach.call(c,f);g.removeListener("dblclick",e);g.removeListener("contextmenu",d)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.DoubleTap");
(function(e){var l=e.map.component;l.zoom.DoubleTap=new ovi.Class({Extends:l.Component,c:"zoom.DoubleTap",n:"0.0.0.1",initialize:function(){function e(b){var h=c.getZoom(b.displayX,b.displayY);d.enabled&&((g=c.getComponentById("panning.Kinetic"))&&g.set("current",null),c.pixelToGeo(b.displayX,b.displayY),c.setZoomLevel(h+1,"default",b.displayX,b.displayY),b.cancel())}var d=this,c,g,b=l.Component.prototype;d.q=d.MAP_2D;d._super({enabled:!0});d.attach=function(f){b.attach.call(d,f);c=f;c.addListener("dbltap",
e)};d.detach=function(f){b.detach.call(d,f);c.removeListener("dbltap",e)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.zoom.GestureEvent");
(function(e){var e=e.map.component,l,h,d=ovi.Array.forEach,c=ovi.Array.indexOf,g=e.Component.prototype,b=["gesturestart","gestureend","gesturechange","touchstart","touchmove","touchend"];e.zoom.GestureEvent=new ovi.Class({Extends:e.Component,c:"zoom.GestureEvent",n:"0.0.0.1",initialize:function(){h=this;h.q=h.MAP_2D;h._super();h.attach=function(c){g.attach.call(h,c);l=c;d(b,function(b){l.addEvent(b)})};h.detach=function(c){g.detach.call(h,c);d(b,function(b){l.removeEvent(b)})}},addListener:function(d,
g){if(c(b,d)>=0)return l.addListener(d,g),!0;return!1},removeListener:function(d,g){if(c(b,d)>=0)return l.removeListener(d,g),!0;return!1}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.Click");
(function(e){var l=e.map.component;l.panning.Click=new ovi.Class({Extends:l.Component,c:"panning.Click",n:"0.0.0.1",initialize:function(e){function d(d){c.enabled&&b.setCenter(b.pixelToGeo(d.targetX,d.targetY),"default")}var c=this,g=l.Component.prototype,b;c._super(ovi.extend({enabled:!0,useKineticPanning:!0},e));c.attach=function(f){g.attach.call(c,f);b=f;b.addListener("click",d)};c.detach=function(f){g.detach.call(c,f);b.removeListener("click",d)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.Tap");
(function(e){var l=e.map.component;l.panning.Tap=new ovi.Class({Extends:l.Component,c:"panning.Tap",n:"0.0.0.1",initialize:function(e){function d(d){c.enabled&&b.setCenter(b.pixelToGeo(d.targetX,d.targetY),"default")}var c=this,g=l.Component.prototype,b;c.q=c.MAP_2D;c._super(ovi.extend({enabled:!0,useKineticPanning:!0},e));c.attach=function(f){g.attach.call(c,f);b=f;b.addListener("tap",d)};c.detach=function(f){g.detach.call(c,f);b.removeListener("tap",d)}}})})(nokia.maps);ovi.provide("nokia.maps.map.HitArea");
(function(){var e=Math,l=e.PI/180,h=e.ceil,d=e.min,c=e.sin,g=e.cos,b=nokia.maps.util,f=b.Point,r=nokia.maps.map.HitArea=new ovi.Class({initialize:function(a,f){var e=(f=[].concat(f)).length,m=e,p,r,s,u,w;this.values=f;for(this.type=a;m--;)isNaN(f[m]=f[m])&&b.d("Given argument is not the array of numbers");a==="rect"&&e>3&&(f=[+f[0],+f[1],+f[2],+f[1],+f[2],+f[3],+f[0],+f[3]],a="poly");if(a==="circle"&&e>2&&(s=+f[2])>0){p=+f[0];r=+f[1];m=d(h(s)*2,40);u=360/m;for(f=[];m--;)w=u*m*l,f.push(p+c(w)*s,r+
g(w)*s);a="poly"}if(a==="poly"&&e&&!(f.length%2))this.lc=f;!this.lc&&b.d("bad polygon")},Statics:{from:function(a){return a instanceof r?a:new r(a.type,a.values?a.values:a.coords)}},hitTest:function(a,b,c){return f.isCoveredBy(a,b,this.lc,c,!0)}})})();ovi.provide("nokia.maps.map.provider.NullObjectProvider");
(function(e){e.map.provider.NullObjectProvider=new ovi.Class({zg:function(){},si:function(){},Dc:function(){},requestBBox:function(){return[]},cancelBBoxRequest:function(){},adopt:function(e){if(e.e)return!1;e.e=this;return e},orphan:function(e){if(e.e!==this)return!1;e.e=null;return e}})})(nokia.maps);ovi.provide("nokia.maps.map.render.Capabilities");
(function(){if(!nokia.maps.util.getConstructor(nokia.maps.map.render.Capabilities))var e=nokia.maps,l={min:0,max:0},h=(e.map.render.Capabilities=function(d){return e.util.proto(d,h,!0,!0)}).prototype={view:{heading:l,tilt:l,incline:l,distance:l,zoom:{min:-1/0,max:1/0}},cam:{fov:{min:70,max:70}},altMode:{GL:!0,OL:!1,SL:!1,SB:!1,WE:!1,WG:!1},provider:{tile:{bmp:!0,gfx:!1,mesh:!1},object:{spatial:!0,marker:!0,decal:!1}},ui:17,capture:!1,ZOOM:1,HEADING:2,TILT:4,INCLINE:8,COORD:16,FOV:32,SIZE:64}})();
ovi.provide("nokia.maps.map.component.panning.Kinetic");(function(e){var l=e.map.component,h=l.panning;if(!e.util.getConstructor(h.Kinetic))h.Kinetic=new ovi.Class({Extends:l.Component,c:"panning.Kinetic",n:"0.0.0.1",initialize:function(d){this._super(ovi.extend({current:null},d))},attach:function(d){this._super(d);d.yh=!0},detach:function(d){this._super(d);d.yh=!1}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.panorama.Click");
(function(e){var l=e.map.component;l.panning.panorama.Click=new ovi.Class({Extends:l.Component,c:"panning.panorama.Click",n:"0.0.0.1",initialize:function(e){function d(d){c.enabled&&d.button===0&&b.setView(b.m.viewForXY(d.targetX,d.targetY),"default")}var c=this,g=l.Component.prototype,b;c.q=c.PANORAMA;c._super(ovi.extend({enabled:!0,useKineticPanning:!0},e));c.attach=function(f){g.attach.call(c,f);b=f;b.addListener("click",d)};c.detach=function(f){g.detach.call(c,f);b.removeListener("click",d)}}})})(nokia.maps);
ovi.provide("nokia.maps.map.component.zoom.Gesture");
(function(e){var l=e.map.component;l.zoom.Gesture=new ovi.Class({Extends:l.Component,c:"zoom.Gesture",n:"0.0.0.1",initialize:function(){this.q=this.MAP_2D;this.onGestureStart=ovi.bind(this,this.onGestureStart);this.onGestureEnd=ovi.bind(this,this.onGestureEnd);this.onTouch=ovi.bind(this,this.onTouch);this._super({enabled:!0})},$c:!1,fd:!1,onGestureStart:function(e){if(this.enabled)this.$c=!0,e.preventDefault()},onGestureEnd:function(e){if(this.enabled)this.fd=this.$c=!1,this.mapDisplay.m.endInteraction(),
e.preventDefault()},onTouch:function(e){if(this.enabled&&this.$c){var d=this.mapDisplay.m,c=e.touches,g=c.length>1,e=e.timeStamp,b=c[0].pageX,f=c[0].pageY,l=g?c[1].pageX:void 0,c=g?c[1].pageY:void 0;this.fd?d.interact(e,b,f,l,c):(d.beginInteraction(d.capabilities.ZOOM|d.capabilities.COORD,null,e,b,f,l,c),this.fd=!0)}},attach:function(e){var d;this._super(this,e);this.mapDisplay=e;this.th=d=new l.zoom.GestureEvent;e.addComponent(d);d.addListener("gesturestart",this.onGestureStart);d.addListener("gestureend",
this.onGestureEnd);d.addListener("touchstart",this.onTouch);d.addListener("touchmove",this.onTouch)},detach:function(e){var d=this.th;this._super(this,e);this.mapDispay=null;e.removeComponent(d);d.removeListener("gesturestart",this.onGestureStart);d.removeListener("gestureend",this.onGestureEnd);d.removeListener("touchstart",this.onTouch);d.removeListener("touchmove",this.onTouch);this.th=null;this.fd=this.$c=!1},enableRotation:function(){},disableRotation:function(){this.Uv=!1},enableZoom:function(){this.fp=
!0},disableZoom:function(){this.fp=!1}})})(nokia.maps);ovi.provide("nokia.maps.map.Object");
(function(e){if(!e.util.getConstructor(e.map.Object)){var l=0,h=0,d=function(c,b){var d=c.Ua(),e=b.Ua(),a,q,k,m=0,p;if(!d||!e)return 0;a=d.length;q=e.length;for(k=a<q?a:q;m<k;m++)if(p=e[m]-d[m])return h?-p:p;return h?a-q:q-a},c={rev:0,sort:function(c,b,f){var e=[],a,q,k=c.length;for(q=0;q<k;q++)((a=c[q]).getIconForRendering||a.drawToTile)&&(b||a.isVisible())&&e.push(a);h=f;e.sort(d);return e},create:function(c){var b=c.t,d;d=null;b&&(d=(d=b.Ua())?d.slice():[],d.push(c.zIndex,b.objects.indexOf(c)));
return d}};nokia.maps.map.Object=new ovi.Class({Extends:e.util.OObject,Mixins:e.dom.EventTarget,Statics:{sortByZInfo:c.sort,CHANGE_SPATIAL:1,CHANGE_VISUAL:2,CHANGE_ZINDEX:4},dispatch:function(c){c.display=this.getDisplay();return e.dom.EventTarget.prototype.dispatch.call(this,c)},initialize:function(c){this.e=new e.map.provider.NullObjectProvider;this.id=l++;c&&"draggable"in c?(c.isDraggable=c.draggable,delete c.draggable,this._super(c),c.draggable=c.isDraggable,delete c.isDraggable):this._super(c);
this.addObserver("*",this.nc,this)},t:null,CHANGE_SPATIAL:1,CHANGE_VISUAL:2,CHANGE_ZINDEX:4,isEventTarget:!0,zIndex:0,visibility:!0,B:"object",ad:function(){return this.ac||(this.ac={})},destroy:function(){var c=this.t;c&&c.objects.remove(this);this.removeAllListeners();this.e=null;this.removeObserver("*",this.nc,this)},getInvalidations:function(c){var b=this.ac;return b?(b[1]>c)*1|(b[2]>c)*2|(b[4]>c)*4:0},nc:function(c,b){this.ja(b,0)},getProvider:function(){return this.e},getParent:function(){return this.t},
getRoot:function(){for(var c=this,b;b=c.t;)c=b;return c},getDisplay:function(){var c=this.getRoot();return c.B==="display"?c:null},isVisible:function(){var c=this,b=!1;do b=c.visibility;while(b&&(c=c.t));return b},ja:function(c,b){var d;d=this.e;var e;b|=c==="zIndex"?4:c==="visibility"?2:0;e=d.Dc(this,b);d=this.ad();b&1&&(d[1]=e);b&2&&(d[2]=e);b&4&&(d[4]=e)},zIndexSetter:function(c){this.bc();return c},eventListenerSetter:function(c){var b=0,d,e;if(c)for(e in this.removeAllListeners(),c)if((b=ovi.type(d=
c[e]))==="array")for(b=0;b<d.length;b+=3)this.addListenerNS(d[b+2],e,d[b],d[b+1]);else b==="function"&&this.addListenerNS(null,e,d,!1)},Ua:function(){var d;if(!(d=this.Bc))d=this.Bc=c.create(this);return d},bc:function(){this.Bc=void 0},adopt:function(c){return c.adopt(this)},orphan:function(){return this.e.orphan(this)}})}})(nokia.maps);ovi.provide("nokia.maps.map._MarkerIcon");
(function(){function e(c){return new b(typeof c==="object"?c.strokeColor?{strokeColor:a(c.strokeColor)}:void 0:{strokeColor:c})}var l=nokia.maps,h=l.map.HitArea,d=l.util,c=d.proto,g=d.Point,b=d.Pen,f=new b({strokeColor:"#FFF"}),r=d.Brush,a=d.ColorHelper.getHex3,q=l.gfx,k=q.GraphicsImage,m=q.IDL,p=q.Color.parseCss,z=[4207599104,4207599105,4207599106,"$Text$"],s=new l.gfx.SvgParser,u=d.pd("shape text textPen pen brush effect"),w=d.flatMerge(d.pd("anchor hitArea"),u),x=new d.Cache(50),v=nokia.maps.map.Sb=
new ovi.Class({Extends:nokia.maps.util.OObject,initialize:function(a){var b;a&&a.shape&&a.shape!==this.shape?(this.shape=this.shapeSetter(b=a.shape),delete a.shape,this._super(a),a.shape=b):(this.shapeSetter(this.shape),this._super(a));this.addObserver("*",this.we)},Statics:{Qn:w,$a:function(a){return a in w},Le:function(a){return!(a in u)},rc:{balloon:['<path style="opacity:0.4;fill:#353535" d="m 19,31 c 0,1.67 -2.69,3 -6,3 c -3.31,0 -6,-1.33 -6,-3 c 0,-1.67 2.69,-3 6,-3 c 3.31,0 6,1.33 6,3 z" /><path style="fill:#Facade01" d="m 13,0 c -3.47,0 -6.73,1.32 -9.19,3.75 C 1.36,7.82 0,9.41 0,12.84 c 0,3.43 1.36,6.64 3.81,9.06 L 13,31 l 9.19,-9.094 c 2.46,-2.43 3.81,-5.63 3.81,-9.06 c 0,-3.43 -1.36,-6.67 -3.81,-9.09 C 19.73,1.32 16.47,0 13,0 z"/><path style="fill:#ffffff" d="m 13,1 c -3.21,0 -6.23,1.23 -8.5,3.47 c -2.26,2.24 -3.5,5.22 -3.5,8.38 c 0,3.16 1.24,6.14 3.5,8.38 l 8.5,8.38 l 8.5,-8.38 c 2.26,-2.24 3.5,-5.22 3.5,-8.38 c 0,-3.16 -1.24,-6.14 -3.5,-8.38 C 19.23,2.23 16.2,1 13,1 z"/><path style="fill:#Facade00;fill-opacity:1" d="m 13,2.19 c -7,0 -10.74,4.96 -10.81,10.65 c 0,3.27 0.95,5.61 3.03,7.66 l 7.79,7.69 l 7.79,-7.69 c 2.07,-2.05 3.02,-4.27 3.03,-7.66 C 23.58,7.07 19.98,2.19 13,2.19 z"/><text x="13" y="18" font-size="10pt" font-family="arial" font-weight="bold" text-anchor="middle" fill="#Facade02">$Text$</text>',
28,36,13,31,"poly",[0,16,0,7,8,0,18,0,26,7,26,16,18,34,8,34]]}},text:"",pen:c({},f),textPen:c({},f),brush:c({},new r({color:"#1080DD"})),shape:"balloon",effect:"none",we:function(a,b){if(b in u)a.c="",a.Va=0},shapeSetter:function(a){var b=v.rc[a]||d.d("shape");this.f=new g(b[1],b[2]);this.anchor=new g(b[3],b[4]);this.hitArea=b[5]?new h(b[5],b[6]):void 0;return a},brushSetter:function(b){return new r(typeof b==="object"?b.color?{color:a(b.color)}:void 0:{color:b})},penSetter:e,textPenSetter:e,textSetter:function(a){return d.sanitizeText(a)},
ue:function(){var a=v.rc[this.shape],b,c,d,f;if(a&&typeof a[0]==="string"){b=z.length;for(c=a[0]=ovi.Array(s.parseSvg('<svg version="1.1" width="'+(d=a[1])+'" height="'+(f=a[2])+'" viewBox="0 0 '+d+" "+f+'">'+a[0]+"</svg>").data);b--;){f=[];for(d=-1;(d=c.indexOf(z[b],d+1))!==-1;)f.push(d);f.length&&(a[7+b]=f)}}return a},bf:function(a){for(var b=[p(this.brush.color,1),p(this.pen.strokeColor,1),p(this.textPen.strokeColor,1),this.text],c=b.length,d=a[0].slice(),f,g;c--;)if(f=a[7+c])for(g=f.length;g--;)d[f[g]]=
b[c];return d},getIcon:function(){var a,b;if(!this.Va){if(!(b=x.get(a=this.fa())))x.add(a,b=new k(new m(this.bf(this.ue()))));this.Va=b}return this.Va},fa:function(){return this.c||(this.c=(this.hasOwnProperty("shape")?this.shape:"").concat(this.text,this.textPen.fa(),"P",this.pen.fa(),"B",this.brush.fa()))}})})();ovi.provide("nokia.maps.map.Marker");
(function(){var e=nokia.maps,l=e.util,h=e.dom,d=e.map,c=e.gfx,g=l.Point,b=l.Strip,f=new g(0,0),r=l.Rectangle,a=d.Sb,q=e.geo,k=d.HitArea,m=q.Coordinate,e=new ovi.Class({Extends:d.Object,initialize:function(b,c){var d;if(this.B==="marker"&&(!c||!("icon"in c)))d=new a,this.set("icon",d.getIcon()),this.set("anchor",d.anchor),this.set("hitArea",d.hitArea);this.Xa={};this._super(c);this.set("coordinate",b,1)},B:"marker",anchor:f,f:f,coordinateSetter:function(a){(a=m.fromObject(a))||l.d("coord");this.Xa=
{};return a},hitAreaSetter:function(a){return!a?a:k.from(a)},anchorSetter:function(a){(a=g.fromObject(a))||l.d("you have to set util.Point");return a},draggableSetter:function(a){return this.isDraggable=a},Qa:function(a){this.f=new g(a.width,a.height);this.sc=1},iconSetter:function(a){ovi.type(a);a instanceof c.Image||(a=c.Image.fromObject(a));a instanceof c.Image||l.d("icon");this.icon=a.F===document?a:a.clone(document);a.state===1?this.Qa(a):this.sc=0;return this.icon},getBoundingBox:function(){return q.BoundingBox.coverAll([this.coordinate])},
getDisplayBoundingBox:function(a){a=a.geoToPixel(this.coordinate).sub(this.anchor);return new r([a,a.add(this.f)])},hitTest:function(a,b,c,d){var a=this.getDisplayBoundingBox(a),f=new g(b,c),e=this.hitArea;return a.contains(f)&&(!e||e.hitTest(b-a.topLeft.x,c-a.topLeft.y,d))},getDisplayOffset:function(a,b,c){return(new g(b,c)).sub(a.geoToPixel(this.coordinate))},ja:function(a,b){a!=="zIndex"&&(b|=a==="coordinate"?1:2);this._super(a,b)},xe:function(a){var b="error";a.state===1&&(this.Qa(a),this.ja("icon",
2),b="load");this.dispatch(new h.Event({type:b,target:this,relatedTarget:a}))},getIconForRendering:function(a){var b=this.icon;a!==document&&(b=b.clone(a));b.state?this.sc||b.state===1&&this.Qa(b):b.prepare(this.xe,this);return b},project:function(a){return this.Xa[a.id]||(this.Xa[a.id]=a.geoToMapPoints(b.stencil(b.LAT_LNG,[this.coordinate.latitude,this.coordinate.longitude])))}});if(d.Marker.isNs)d.Marker=e})();ovi.provide("nokia.maps.map.StandardMarker");
(function(){function e(c,d,b){c.V.set(d,b);if(d==="shape")c.f=c.V.f,c.set("anchor",c.V.anchor),c.set("hitArea",c.V.hitArea);return c.V[d]}var l=nokia.maps,h=l.util,d=l.map.Sb,l=nokia.maps.map.StandardMarker=new ovi.Class({Extends:nokia.maps.map.Marker,initialize:function(c,g){var b=this.V=new d(h.flatMerge({},g,1,d.$a));h.flatMerge(this,b,1,d.$a);this.f=b.f;this._super(c,h.flatMerge({},g,1,d.Le))},B:"standardmarker",shapeSetter:function(c){return e(this,"shape",c)},textSetter:function(c){return e(this,
"text",c)},textPenSetter:function(c){return e(this,"textPen",c)},penSetter:function(c){return e(this,"pen",c)},brushSetter:function(c){return e(this,"brush",c)},getIconForRendering:function(c){this.set("icon",this.V.getIcon());return this._super(c)}});h.flatMerge(l.prototype,d.prototype,!0,d.$a)})();ovi.provide("nokia.maps.map.component.objects.DragMarker");
(function(e){var l=e.util.Point,e=e.map,h=e.component,d=e.Marker,c=d.prototype.B,g=e.StandardMarker.prototype.B;h.objects.DragMarker=new ovi.Class({Extends:h.Component,c:"objects.DragMarker",n:"0.0.0.1",dragSourceOpacity:1,dragIconOpacity:0.5,initialize:function(b){function f(a){var b=a.dataTransfer,f=b&&b.getData("application/map-drag-type"),e=b&&b.getData("application/map-drag-object");if((f===c||f===g)&&e instanceof d){if(e.t)b.dropEffect="none";else if(b.allows("move"))b.dropEffect="move";else{b.dropEffect=
"none";a.cancel();return}f=b.getData("application/map-drag-object-offset")||new l(0,0);e.set("coordinate",s.pixelToGeo(a.displayX-f.x+e.anchor.x,a.displayY-f.y+e.anchor.y));b.dropEffect!=="none"&&s.objects.add(e);a.cancel()}else b.dropEffect="none"}function e(a){var b=a.dataTransfer,d=b&&b.getData("application/map-drag-type"),f=b&&b.getData("application/map-drag-object");if(d===c||d===g)b.dropEffect=f.t?"move":"copy",a.cancel()}function a(a){var b=a.dataTransfer,d=b&&b.getData("application/map-drag-type"),
f=b&&b.getData("application/map-drag-object");if(d===c||d===g)b.dropEffect=f.t?"move":"copy",a.cancel()}function q(a){var b=(a=a.dataTransfer)&&a.getData("application/map-drag-type"),d=a&&a.getData("application/map-drag-object");a&&a.getData("application/map-drag-object-display");if(b===c||b===g){d.removeListener("dragend",q,!0);if(a.dropEffect==="move"&&!s.contains(d))dragMarkerParent=d.t,dragMarkerParent.objects.remove(d);d.icon.opacity=1;d.ja("icon",2)}}function k(a){var b=a.dataTransfer,b=b&&
b.getData("application/map-drag-type");(b===c||b===g)&&a.stopImmediatePropagation()}function m(a){if(p.enabled){var b,c,f,g=a.target,e=a.dataTransfer;if(g instanceof d&&g.isDraggable)c=g.getDisplayBoundingBox(s),b=a.displayX-c.topLeft.x,c=a.displayY-c.topLeft.y,f=g.getIconForRendering(document),e.setDragImage(f.createElement(p.dragIconOpacity),-b,-c),g.icon.opacity=p.dragSourceOpacity,g.ja("icon",2),e.setData("application/map-drag-type",g.B),e.setData("application/map-drag-object",g),e.setData("application/map-drag-object-offset",
new l(b,c)),e.effectAllowed="all",e.setData("application/map-drag-object-display",s),g.insertListener("dragend",q,!0),a.stopImmediatePropagation()}}var p=this,z=h.Component.prototype,s;p.q=p.MAP_2D|p.GLOBE;p._super(ovi.extend({enabled:!0,useKineticPanning:!0},b));p.attach=function(b){z.attach.call(p,b);s=b;s.addListener("dragstart",m);s.addListener("drag",k);s.addListener("dragend",q);s.addListener("dragenter",a);s.addListener("dragover",e,!0);s.addListener("drop",f)};p.detach=function(b){z.detach.call(p,
b);s.removeListener("dragstart",m);s.removeListener("drag",k);s.removeListener("dragend",q);s.removeListener("dragenter",a);s.removeListener("dragover",e);s.removeListener("drop",f)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.panning.Drag");
(function(e){function l(b){return 1*b.altKey+2*b.ctrlKey+4*b.metaKey+8*(b.button===2||b.button===0&&(b.shiftKey||h&&b.ctrlKey))}var h=e.dom.Page.platform.mac,d=e.map,c=d.component,g=new d.render.Capabilities,b={duration:function(){return 600},ease:e.util.animation.easeFunctions.LINEAR,power:function(){return 1}};c.panning.Drag=new ovi.Class({Extends:c.Component,c:"panning.Drag",n:"0.0.0.1",initialize:function(d){function e(b){k.enabled&&k.A&&(a(b),p.endInteraction(),p.setTransition(p.Ca.TRANSITION.AUTO))}
function a(a){var b=a.dataTransfer;if(k.enabled&&k.A&&b&&b.getData("application/map-drag-type")==="map"){var b=a.deltaX,c=a.deltaY;l(a)!==z?h(a):(b||c)&&p.interact(a.timeStamp,a.displayX,a.displayY)}}function h(c){var d;if(k.enabled&&k.A)d=c.dataTransfer,z=l(c),d.cursor=z&8?"move":"hand",d.lift=!1,d.setData("application/map-drag-type","map"),d.setData("application/map-drag-object",p),d.setData("application/map-drag-object-offset",void 0),p.setTransition(p.Ca.TRANSITION.NONE),p.beginInteraction(z&
8?g.HEADING|g.TILT:g.COORD,p.yh?b:"",c.timeStamp,c.displayX,c.displayY),a(c)}var k=this,m=c.Component.prototype,p,z;k.A=!0;k.q=k.PANORAMA|k.MAP_2D|k.GLOBE;k._super(ovi.extend({enabled:!0,useKineticPanning:!0},d));k.attach=function(b){m.attach.call(k,b);p=b;p.addListener("dragstart",h);p.addListener("drag",a);p.addListener("dragend",e)};k.detach=function(b){m.detach.call(k,b);p.removeListener("dragstart",h);p.removeListener("drag",a);p.removeListener("dragend",e)}}})})(nokia.maps);ovi.provide("nokia.maps.map.component.Behavior");
(function(e){var e=e.map.component,l=e.zoom,h=e.panning,d=new ovi.Array([e.objects.DragMarker,l.MouseWheel,l.DoubleClick,l.DoubleTap,l.Gesture,h.Drag,h.Kinetic,h.panorama.Click]);e.Behavior=new ovi.Class({Extends:e.Component,c:"Behavior",n:"0.0.0.1",q:this.PANORAMA|this.MAP_2D,initialize:function(){this.hf=new ovi.Array},attach:function(c){d.forEach(function(d){d&&this.hf.push(c.addComponent(new d))},this);this.mapDisplay=c},detach:function(){this.hf.forEach(function(c){this.mapDisplay.removeComponent(c)},
this);this.hf.length=0;delete this.mapDisplay}})})(nokia.maps);ovi.provide("nokia.maps.behavior._packaging.package-all");})();
