(function(){ovi.provide("nokia.maps.gfx.SvgPainter");
(function(){if(document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure","1.1")){var e=nokia.maps.gfx,l=e.Painter,h=e.IDL,d=e.Color,c=h.opcodes,g=h.identifierToAttribute,b=nokia.maps.dom,f=nokia.maps.util.d,r=!("naturalWidth"in new Image),l=Math,a=l.sin,q=l.acos,k=l.sqrt,m=l.pow,l=nokia.maps.gfx.Painter,p=d.getCssHex,z=4711,s=l.Ag,u=function(a,b,c,d,f){a.setAttribute("width",b);a.setAttribute("height",c);d!==void 0&&(a.setAttribute("x",d),a.setAttribute("y",f))},w=function(a){a.setAttribute("preserveAspectRatio",
"none")},e=nokia.maps.gfx.SvgPainter=new ovi.Class({Extends:nokia.maps.gfx.Painter,Xf:function(a){this.Wc=a;this.qd={}},L:function(a){this.qd[a]||(this.qd[a]=this.Wc.createElementNS("http://www.w3.org/2000/svg",a));return this.qd[a].cloneNode(!0)},ni:function(b,c,f,e,g,h,p){var l=this.ma,r=this.L("text"),s=k(m(e-c,2)+m(g-f,2)),e=(e-c)/s,g=q(e)+(g<f)*Math.PI,g=a(g),z=nokia.maps.util.FontHelper.parse(l.font);r.setAttribute("transform",["matrix(",s*e,s*g,s*-g,s*e,c,f,")"].join(" "));r.setAttribute("x",
0);r.setAttribute("y",0);r.setAttribute("fill-opacity",d.percentOf(l.opacity&255));h&&this.Wb(r);p&&this.tc(r);r.setAttribute("text-anchor",l.textAlign.replace("center","middle"));z.style&&r.setAttribute("font-style",z.style);z.variant&&r.setAttribute("font-variant",z.variant);z.weight&&r.setAttribute("font-weight",z.weight);z.size&&r.setAttribute("font-size",z.size);z.family&&r.setAttribute("font-family",z.family);r.appendChild(this.Wc.createTextNode(b));return r},Zg:function(a){var b=this.L("path");
b.setAttribute("d",(a[0]!=="M"?"m 0 0 ":"")+a.join(" "));b.setAttribute("fill","none");return b},Wb:function(a){var b=this.ma;a.setAttribute("fill",p(b.fillColor));a.setAttribute("fill-opacity",d.percentOf(b.fillColor&255)*b.opacity)},tc:function(a){var b=this.ma,c=b.lineCap;a.setAttribute("stroke",p(b.strokeColor));a.setAttribute("stroke-opacity",d.percentOf(b.strokeColor&255)*b.opacity);a.setAttribute("stroke-width",b.lineWidth+"px");a.setAttribute("stroke-linecap",c==="butt"?"flat":c);a.setAttribute("stroke-linejoin",
b.lineJoin);a.setAttribute("stroke-miterlimit",b.miterLimit)},createMarkup:function(a){var b=document,a=this.createElement(a,b),b=b.createElement("DIV");b.appendChild(a);return b.innerHTML},updateElement:function(a,c,d){var f=c.ownerDocument,e=a.data[1],g=a.data[2];b.Ob(c);this.pa(a,this.ah(c,e,g),f);c.style.opacity=c.$n$opacity=s(d);c.$n$width=e;c.$n$height=g},ah:function(a,b,c){this.Xf(a.ownerDocument);a=a.appendChild(this.L("svg"));w(a);u(a,a.style.width=b+"px",a.style.height=c+"px");a.setAttribute("viewBox",
"0 0 "+b+" "+c);a.style.overflow="hidden";return a},createElement:function(a,b,c){(!a||!a.data)&&f("SvgPainter.createElement: Illegal IDL given");var d=(b=b||document).createElement("DIV"),e=a.data[1],g=a.data[2];d.$n$width=e;d.$n$height=g;d.style.opacity=d.$n$opacity=s(c);this.pa(a,this.ah(d,e,g),b);return d},setOpacity:function(a,b){a.style.opacity=a.$n$opacity=s(b);return this},setScale:function(a,b){var c=a.childNodes,d=c.length,f,e=b.x*a.$n$width+"px",g=b.y*a.$n$height+"px";a.style.width=e;for(a.style.height=
g;f=c[--d];)if(f.nodeName==="svg"){w(f);f.style.width=e;f.style.height=g;break}},pa:function(a,b,d){var a=a.data,e,k,m=[],p,q,l,s,L,N,G,M,$,F,Z,ba,J,V,H,P;a[e=0]!==c.BEGIN_2D_IMAGE&&f("SvgPainter.createElement: Illegal opcode in IDL");e+=3;for(this.ma=new h;k=a[++e];)k===c.BEGIN_2D_IMAGE?e+=3:k===c.BEGIN_PATH?m.length&&(m=[]):k===c.MOVE_TO?m.push("M",a[++e],a[++e]):k===c.LINE_TO?m.push("L",a[++e],a[++e]):k===c.BEZIER_CURVE_TO?m.push("C",a[++e],a[++e],a[++e],a[++e],a[++e],a[++e]):k===c.FILL?(p=this.Zg(m),
this.Wb(p),a[e+1]===c.STROKE&&(++e,this.tc(p)),b.appendChild(p)):k===c.STROKE?(p=this.Zg(m),this.tc(p),a[e+1]===c.FILL&&(++e,this.Wb(p)),b.appendChild(p)):k===c.SET?this.ma[g[a[++e]]]=a[++e]:k===c.DRAW_IMAGE||k===c.DRAW_IDL?(p=a[++e],N=a[++e],G=a[++e],M=a[++e],$=a[++e],F=a[++e],Z=a[++e],ba=a[++e]/M,J=a[++e]/$,V=a[++e].rows,l=l||this.L("defs"),s=l.appendChild(this.L("clipPath")),s.setAttribute("id",L="clp"+z++),k===c.DRAW_IMAGE&&p.nodeName!=="CANVAS"&&r?(H=new Image,H.src=p.src):H=p,P=H.naturalWidth||
H.width,H=H.naturalHeight||H.height,u(s.appendChild(this.L("rect")),M*ba*((N+M>P?P-N:M)/M),$*J*((G+$>H?H-G:$)/$),F,Z),s=this.L("g"),s.setAttribute("transform","matrix("+V[0][0]+","+V[1][0]+","+V[0][1]+","+V[1][1]+","+V[0][3]+","+V[1][3]+")"),s.setAttribute("clip-path","url(#"+L+")"),k===c.DRAW_IMAGE?(k=s.appendChild(this.L("image")),k.setAttribute("opacity",this.ma.opacity),w(k),u(k,P*ba,H*J,F-N*ba,Z-G*J),k.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href",p.nodeName==="CANVAS"?p.toDataURL():
p.src)):(k=s.appendChild(this.L("g")),k.setAttribute("transform","translate("+(F-N*ba)+" "+(Z-G*J)+") scale("+ba+" "+J+")"),N=this.ma,this.pa(p,k,d),this.ma=N),b.appendChild(s),b.appendChild(l)):k===c.SAVE?this.ma.saveState():k===c.RESTORE?this.ma.restoreState():(p=k===c.FILL_TEXT,(q=k===c.STROKE_TEXT)||p?b.appendChild(this.ni(a[++e],a[++e],a[++e],a[++e],a[++e],p,q)):k===c.CLOSE_PATH&&m.push("Z"))}});if(!l.defaultPainter)l.defaultPainter=e}})();ovi.provide("nokia.maps.gfx._packaging.package-svg");})();