(function(){ovi.provide("nokia.maps.routing.WaypointParameterList");
nokia.maps.routing.WaypointParameterList=new ovi.Class({initialize:function(){this.waypointList=[]},addCoordinate:function(e){this.waypointList.push(e)},addPlace:function(e){this.waypointList.push(e)},addLocation:function(e){this.waypointList.push(e)},size:function(){return this.waypointList.length},clear:function(){this.waypointList=[]},toCoordinates:function(){var e=[],l,h,d;l=0;for(h=this.waypointList.length;l<h;l++)d=this.waypointList[l],"latitude"in d&&"longitude"in d?this.Cv(d,e):"locations"in
d?this.Dv(d,e):("displayPosition"in d||"navigationPosition"in d)&&this.wr(d,e);return e},Cv:function(e,l){l.push(e)},Dv:function(e,l){for(var h=0,d=e.locations.length;h<d;h++)this.wr(e.locations[h],l)},wr:function(e,l){e.displayPosition?l.push(e.displayPosition):e.navigationPosition&&l.push(e.navigationPosition)}});ovi.provide("nokia.maps.routing.Maneuver");ovi.provide("nokia.maps.routing.Mode");ovi.provide("nokia.maps.routing.Route");ovi.provide("nokia.maps.routing.RouteLeg");ovi.provide("nokia.maps.routing.RouteSegment");
ovi.provide("nokia.maps.routing.RouteSummary");ovi.provide("nokia.maps.routing.ServiceError");ovi.provide("nokia.maps.routing.Waypoint");ovi.provide("nokia.maps.routing.component.IsolineResultSet");(function(e){e.routing.component.IsolineResultSet=new ovi.Class({initialize:function(l,h){var d=this.container=new e.map.Container,c=h||{},g,b=e.map.Polygon;g=c.brush||{color:"#00F4"};c=c.pen||{strokeColor:"#00F8",lineWidth:5};l&&(o=new b(l,{pen:c,brush:g}),d.objects.add(o))},container:null})})(nokia.maps);
ovi.provide("nokia.maps.routing.navteq.protocol");
nokia.maps.routing.navteq.protocol={Mode:{type:1,transportModes:1,options:1,trafficMode:1},wf:function(e){return e.latitude+","+e.longitude},Av:function(e){for(var l="",h=e.locations,e=0;e<h.length;e++)l+=this.Lq(h[e],e);return l},Lq:function(e,l){var h="",d,c;(l||0)===0&&e.displayPosition&&(h+=this.wf(e.displayPosition));if(d=e.navigationPositions)for(c=0;c<d.length;c++)h+="!"+this.wf(d[c]),e.address&&e.address.street&&(h+=";"+encodeURIComponent(e.address.street));else e.navigationPosition?(h+="!"+
this.wf(e.navigationPosition),e.address&&e.address.street&&(h+=";"+encodeURIComponent(e.address.street))):throwIllegalArgument("navigation position is not specified in location!");return h}};ovi.provide("nokia.maps.routing.component.ContextMenuHandler");
(function(e){var l=e.config.routing,h=e.map,d=e.routing,c=d.WaypointParameterList,g=l&&l.protocol&&l.protocol.indexOf("62")>0,b={type:"shortest",transportModes:["car"],options:""};e.map.component.ContextMenu.routingHandler=e.routing.component.ContextMenuHandler=function(e,l){function a(){var a=w.Xv;a&&x.objects.remove(a)}function q(b,c,d){var r;var f;a();if(d==="finished"&&(r=(f=(b=b.routes[0])&&b.shape,b=f)&&new h.Polyline(b,{pen:{lineWidth:6,strokeColor:"#05BA",lineJoin:"round"},arrows:!0}),b=r))x.objects.add(b),
u.mapDisplay.zoomTo(x.getBoundingBox(),null,"default"),w.Xv=b}function k(){var e;a();if(w.zc){e=0;for(var f=w.zc.length;w.zc&&e<f;e++)w.zc[e].set("text",e+1)}w.Wa&&w.Wa.state==="started"&&w.Wa.cancel();if(w.hg&&w.zf){z=new c;z.addCoordinate(w.hg.coordinate);for(s=0;w.zc&&s<w.zc.length;s++)z.addCoordinate(w.zc[s].coordinate);z.addCoordinate(w.zf.coordinate);e=w.Wa=new d.Manager;e.addObserver("state",q);e.calculateRoute(z,g?[b]:b)}}var m=e.target,p,z,s,u=this,w=u.Zv||(u.Zv={}),x=w.container||(w.container=
new h.Container);u.mapDisplay.contains(x)||u.mapDisplay.objects.add(x);m instanceof h.Marker&&m.isRoutingMarker?l.addEntry("__i18n_rightClickMenu.removeRoutePoint__",function(){m===w.hg?w.hg=null:m===w.zf?w.zf=null:w.zc&&(idx=w.zc.indexOf(m))>=0&&w.zc.splice(idx,1);x.objects.remove(m);k()},1):(p=u.mapDisplay.pixelToGeo(e.displayX,e.displayY),l.addEntry("__i18n_rightClickMenu.setStartWaypoint__",function(){w.hg?w.hg.set("coordinate",p):x.objects.add(w.hg=new h.StandardMarker(p,{text:"A",isRoutingMarker:!0}));
k()},1),l.addEntry("__i18n_rightClickMenu.addWaypoint__",function(){var a=w.zc||(w.zc=new ovi.Array),b=new h.StandardMarker(p,{isRoutingMarker:!0});a.push(b);x.objects.add(b);k()},1),l.addEntry("__i18n_rightClickMenu.setDestinationWaypoint__",function(){w.zf?w.zf.set("coordinate",p):x.objects.add(w.zf=new h.StandardMarker(p,{text:"B",isRoutingMarker:!0}));k()},1))}})(nokia.maps);ovi.provide("nokia.maps.routing.Manager");
(function(e){var l=e.routing.Manager=new ovi.Class({Extends:e.util.OObject,initialize:function(h,d){var c=h||{};this.xa=d||new e.Config;if(this.constructor===l)return new l.Hb(c);this._super(c)},destroy:function(){this.Hb=null},Statics:{setDefImpl:function(e){return this.Hb||(this.Hb=e),!1}}})})(nokia.maps);ovi.provide("nokia.maps.routing.navteq.protocolV62");
nokia.maps.routing.navteq.protocolV62=ovi.extend({},nokia.maps.routing.navteq.protocol,{getCalculateRouteUrl:function(e,l,h,d,c){var g=[],b,f,r=[];(!(l instanceof nokia.maps.routing.WaypointParameterList)||ovi.type(h)!="array")&&nokia.maps.util.d("The argument in calculateRoute request is illegal");l.size()<2&&nokia.maps.util.d("Less than two waypoints submitted to calculateRoute call");e+="routeattributes=shape&maneuverattributes=direction,shape&jsonAttributes=1";for(b in d)e+="&"+b+"="+d[b];d=l.waypointList;
for(l=0;l<d.length;l++)if(b=d[l],"latitude"in b&&"longitude"in b)e+="&waypoint"+l+"=geo!"+this.wf(b);else if("locations"in b)e+="&waypoint"+l+"=street!"+this.Av(b);else if("displayPosition"in b||"navigationPositions"in b||"navigationPosition"in b)e+="&waypoint"+l+"=street!"+this.Lq(b);e+="&language="+c;for(l=0;l<h.length;l++){c=h[l];for(f in c)this.Mode[f]||nokia.maps.util.d('the argument "'+f+'" in mode of calculateRoute Request is illegal');c.type&&(g[g.length]=c.type);c.transportModes&&(g[g.length]=
c.transportModes.join(","));c.trafficMode&&(g[g.length]="traffic:"+c.trafficMode);d=c.options||[];ovi.type(d)=="string"&&(d=d.split(","));if(d){for(c=b=0;c<d.length;c++)switch(d[c]){case "avoidTollroad":r[b++]="tollroad:-1";break;case "avoidMotorway":r[b++]="motorway:-1";break;case "avoidBoatFerry":r[b++]="boatFerry:-1";break;case "avoidRailFerry":r[b++]="railFerry:-1";break;case "avoidPublicTransport":r[b++]="publicTransport:-1";break;case "avoidTunnel":r[b++]="tunnel:-1";break;case "avoidDirtRoad":r[b++]=
"dirtRoad:-1";break;case "avoidPark":r[b++]="park:-1";break;case "preferHOVLane":r[b++]="HOVLane:1";break;case "avoidStairs":r[b++]="stairs:-1"}g[g.length]=r.join(",");r=[]}g.length!=0&&(e+="&mode"+l+"="+g.join(";"),g=[])}return e}});ovi.provide("nokia.maps.routing.component.RouteResultSet");
(function(e){function l(c,b){return c[b==="walk"?"originalPosition":"mappedPosition"]}var h=e.map,d=h.StandardMarker,c=e.util;e.routing.component.RouteResultSet=new ovi.Class({initialize:function(e,b){var f=(this.container=new h.Container).objects,r=e.waypoints,a=e.mode.transportModes,q;q=e.shape;var k;q&&f.add((new h.Polyline(q,{pen:new c.Pen({strokeColor:"#05E8",lineWidth:7}),arrows:new c.Arrows})).set(b));if(r){q=r.length-1;f.add(new d(l(r[0],a),{text:"A",identifier:"waypoints"}));for(k=1;k<q;k++)f.add(new d(l(r[k],
a),{identifier:"waypoints",pos:k-1}));f.add(new d(l(r[q],a),{text:"B",identifier:"waypoints"}))}}})})(nokia.maps);ovi.provide("nokia.maps.routing._packaging.package");ovi.provide("nokia.maps.routing.navteq.Manager");
(function(e){function l(){var b=d.serviceMode,c=nokia.maps.config.routing.baseUrl,e=nokia.maps.config.routing["secure.baseUrl"];b==="cit"&&nokia.maps.config.routing.protocol==="nokia.maps.routing.navteq.protocolV62"&&(b="st");a.setDefaultsNS(p,{baseUrl:c?c.replace("{serviceMode}",b?"."+b:""):"","secure.baseUrl":e?e.replace("{serviceMode}",b?"."+b:""):"","calculateroute.interface":"calculateroute.json"})}var h=e.util,d=h.getRootNameSpace("nokia.maps").Settings,c=h.d,g=e.geo,b=g.BoundingBox,f=g.Coordinate,
r=g.Shape,a=e.Config,q=h.isArray,k=h.services,m=e.net.Request,p="routing",e=nokia.maps.routing.navteq.Manager=new ovi.Class({initialize:function(a,b){this.qa=new m(m.JSONP,{callbackKey:"jsoncallback",autoSkip:!0});this.Jv=ovi.buildNS(nokia.maps.config.routing.protocol);this.addObserver("_shapeParsed",this.ds);this._super(a,b)},Extends:nokia.maps.routing.Manager,Statics:{Yp:function(){var a={waypoint:"waypoints",leg:"legs",link:"links",maneuver:"maneuvers",feature:"features"};return function(b){for(var c=
[],d="";b;){for(var e in b)if(d=a[e],a[e]?(b[a[e]]=b[e],delete b[e]):e=="_type"?delete b[e]:d=e,q(b[d])){if(e!="Shape"&&e!="TransportModes")for(var f=0;f<b[d].length;f++)c[c.length]=b[d][f]}else typeof b[d]=="object"&&(c[c.length]=b[d]);c.length>0?b=c.pop():(delete c,b=!1)}}}()},state:"initial",state:"initial",routes:[],wx:"shape",px:"direction,shape",ej:{},ds:!1,gn:0,fn:0,getRoutes:function(){return this.routes},getErrorCause:function(){return this.state=="failed"?this.sa:null},calculateRoute:function(a,
b){var c=k.addNlpParams(this.Jv.getCalculateRouteUrl(k.getBaseURL(this.xa,p,"calculateroute"),a,b,this.ej,d.defaultLanguage));this.Ow=c;this.Mt=this.qa.send(c,ovi.bind(this,this.calculateRouteCallback));this.set("state","started",!0)},clear:function(){this.routes=[];this.isolines=[];this.set("state","cleared")},metricSystemSetter:function(a){if(a===void 0||a==="imperial"||a==="metric")return a?this.ej.metricSystem=a:delete this.ej.metricSystem,a;else delete this.ej.metricSystem,c("Metric system is invalid")},
calculateRouteCallback:function(a){this.routes=this.Yv(a)},cancel:function(){this.qa.cancelAll();this.set("state","cancelled")},ds:function(a,b,c){if(c)a.set("state","finished"),a.set("_shapeParsed",!1),a.gn=0,a.fn=0},Yv:function(a){var c=a.id,d=a.response;if(a.timeout)this.sa=this.Mb({type:"SystemError",subtype:"Timeout",details:"request times out"}),this.set("state","failed");else if(d.error||d.type&&d.subtype)this.sa=this.Mb(d.error||d),this.set("state","failed");else{nokia.maps.routing.navteq.Manager.Yp(d);
for(var a=d.response.route,e,g,k,d=0;d<a.length;d++){this.gi(a[d],c);for(e=0;e<a[d].waypoints.length;e++)this.Ue(a[d].waypoints[e]);if(a[d].boundingBox)a[d].boundingBox=b.coverAll([new f(a[d].boundingBox.topLeft.latitude,a[d].boundingBox.topLeft.longitude,void 0,!0),new f(a[d].boundingBox.bottomRight.latitude,a[d].boundingBox.bottomRight.longitude,void 0,!0)]);this.Gl(a[d]);if(a[d].mode.features){a[d].mode.options=[];for(e=0;e<a[d].mode.features.length;e++)a[d].mode.options.push(this.Zt[a[d].mode.features[e].value]);
delete a[d].mode.features}if(a[d].legs)for(e=0;e<a[d].legs.length;e++){this.Ue(a[d].legs[e].start);this.Ue(a[d].legs[e].end);for(g=0;g<a[d].legs[e].maneuvers.length;g++)k=a[d].legs[e].maneuvers[g],k.shape&&this.gi(k,c),k.position=new f(k.position.latitude,k.position.longitude,void 0,!0)}}return a}},Gl:function(a){a.getStart=function(){return a.waypoints[0]};a.getDestination=function(){return a.waypoints[a.waypoints.length-1]};a.getManeuvers=function(){for(var b=[],c=0;c<a.legs.length;c++)b=b.concat(a.legs[c].maneuvers);
return b}},Ue:function(a){a.linkId&&delete a.linkId;a.mappedPosition=new f(a.mappedPosition.latitude,a.mappedPosition.longitude,void 0,!0);a.originalPosition&&(a.originalPosition=new f(a.originalPosition.latitude,a.originalPosition.longitude,void 0,!0))},gi:function(a,b){var c=this;c.gn++;r.fromLatLngArray(a.shape.join(",").split(","),!1,function(d){c.fn++;if(c.Mt==b)a.shape=d,c.gn==c.fn&&c.set("_shapeParsed",!0)})},Zt:{tollroad:"avoidTollroad",motorway:"avoidMotorway",boatFerry:"avoidBoatFerry",
railFerry:"avoidRailFerry",publicTransport:"avoidPublicTransport",tunnel:"avoidTunnel",dirtRoad:"avoidDirtRoad",park:"avoidPark",HOVLane:"preferHOVLane",stairs:"avoidStairs"},Mb:function(a){var b=a.details;a.additionalData&&a.additionalData.length&&(b+=" Key: "+a.additionalData[0].key+", Value: "+a.additionalData[0].value);return{type:a.type.charAt(0).toLowerCase()+a.type.substr(1),subtype:a.subtype.charAt(0).toLowerCase()+a.subtype.substr(1),message:b}}});nokia.maps.routing.Manager.setDefImpl(e);
d.addObserver("serviceMode",l);l()})(nokia.maps);ovi.provide("nokia.maps.routing._packaging.package-nlp");})();
